In [10]:
import sqlalchemy as sqla
import time
import geopandas as gpd
import pandas as pd
import trimesh
import shapely
from shapely.geometry import Polygon, MultiPolygon, shape, Point
from geopandas import GeoDataFrame
from shapely.ops import triangulate
import numpy as np
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import subprocess
import sys
import shapely.wkt
import shapely.ops
import psycopg2
from psycopg2.extensions import register_adapter, AsIs
psycopg2.extensions.register_adapter(np.int64, psycopg2._psycopg.AsIs)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None  # default='warn'

## Connect to database

In [11]:
# Chose the DB 'postgresql+psycopg2://postgres:123456@localhost:5432/GEO2020'
db_input = input ("What database should we use?\n\n") 
# The following data uses data connected at our database

# Create the sqlalchemy engine
db_engine = sqla.create_engine(db_input) #is taken by pd.read_sql_query function later on

# Chose the climate file 'C:/Users/JINYUZHEN/Desktop/study/GEO2020/Python/EPW_citysim.cli'
cli_input = input("And what climate file?\n\n")
st = time.time()

# Test connection
try:
    db_connection = db_engine.connect()
except Exception as exc:
    print("\nCouldn't connect to the database\n")
    try:
        print(exc.message, exc.args)
    except:
        pass
    sys.exit()

What database should we use?

 postgresql+psycopg2://postgres:123456@localhost:5432/TEST_ADE
And what climate file?

 C:/Users/JINYUZHEN/Desktop/study/GEO2020/Python/EPW_citysim.cli

## Download geometry data from the database

In [4]:
# Enter the interest area for selection
x_min_selection, y_min_selection, x_max_selection, y_max_selection, EPSG, BUFFER = input ("Enter the interest area bbox, EPSG and BUFFER").split()

Enter the interest area bbox, EPSG and BUFFER 0 -30 70 70 28992 50

In [5]:
# Calculate the buffer area bbox for surrounding objects selection
x_min_selection_buffer = str(float(x_min_selection) - float(BUFFER))
y_min_selection_buffer = str(float(y_min_selection) - float(BUFFER))
x_max_selection_buffer = str(float(x_max_selection) + float(BUFFER))
y_max_selection_buffer = str(float(y_max_selection) + float(BUFFER))

In [8]:
# Download lod2 buildings geometry envelope from the database
geometry_envelope = gpd.read_postgis("SELECT thematic_surface.objectclass_id, thematic_surface.building_id, thematic_surface.lod2_multi_surface_id, surface_geometry.gmlid, surface_geometry.geometry, cityobject.gmlid as parent_gmlid, surface_geometry.cityobject_id FROM thematic_surface LEFT JOIN surface_geometry ON thematic_surface.lod2_multi_surface_id = surface_geometry.parent_id LEFT JOIN cityobject ON thematic_surface.building_id = cityobject.id WHERE surface_geometry.geometry && st_makeenvelope(%s,%s,%s,%s,%s) ORDER BY parent_gmlid"%(x_min_selection, y_min_selection, x_max_selection, y_max_selection, EPSG), db_engine, geom_col = "geometry")
# Download trees geometry envelope from the database
tree_envelope = gpd.read_postgis("SELECT g.* from (SELECT o.id::bigint AS co_id, ST_SetSRID(ST_Affine(ST_Collect(sg.implicit_geometry),split_part(lod2_implicit_transformation, ' ', 1)::numeric,0,0,0,split_part(lod2_implicit_transformation, ' ', 6)::numeric,0,0,0,split_part(lod2_implicit_transformation, ' ', 11)::numeric,ST_X(o.lod2_implicit_ref_point),ST_Y(o.lod2_implicit_ref_point),ST_Z(o.lod2_implicit_ref_point)),srs.srid)::geometry(MultiPolygonZ, 28992) AS geom FROM citydb.solitary_vegetat_object AS o INNER JOIN citydb.implicit_geometry AS ig ON (ig.id = o.lod2_implicit_rep_id) INNER JOIN citydb.surface_geometry AS sg ON (sg.root_id = ig.relative_brep_id), citydb.database_srs AS srs GROUP BY o.id,srs.srid)g WHERE g.geom && st_makeenvelope(%s,%s,%s,%s,%s)"%(x_min_selection_buffer, y_min_selection_buffer, x_max_selection_buffer, y_max_selection_buffer, EPSG), db_engine, geom_col = "geom")
# Download terrain geometry envelope from the database
terrain_envelope = gpd.read_postgis("SELECT surface_geometry.gmlid, surface_geometry.id, surface_geometry.geometry FROM surface_geometry, tin_relief WHERE surface_geometry.parent_id = tin_relief.surface_geometry_id AND surface_geometry.geometry && st_makeenvelope(%s,%s,%s,%s,%s)"%(x_min_selection_buffer, y_min_selection_buffer, x_max_selection_buffer, y_max_selection_buffer, EPSG), db_engine, geom_col = "geometry")

In [9]:
# Show the number of buildings inside the study area
number_of_building = len(pd.unique(geometry_envelope['building_id']))
print('number of selected buildings', number_of_building)

number of selected buildings 0

In [735]:
geometry_envelope.head(5)

,objectclass_id,building_id,lod2_multi_surface_id,gmlid,geometry,parent_gmlid,cityobject_id
0,34,5,286,id_building_1_polygon_5,"POLYGON Z ((0.00000 0.00000 0.00000, 10.00000 ...",id_building_01,51
1,33,5,99,id_building_1_polygon_2,"POLYGON Z ((5.00000 0.00000 15.00000, 10.00000...",id_building_01,12
2,34,5,274,id_building_1_polygon_4,"POLYGON Z ((0.00000 10.00000 0.00000, 0.00000 ...",id_building_01,44
3,36,5,263,id_building_1_polygon_cs1,"POLYGON Z ((10.00000 10.00000 10.00000, 10.000...",id_building_01,17
4,35,5,135,id_building_1_polygon_3,"POLYGON Z ((0.00000 0.00000 0.00000, 0.00000 1...",id_building_01,15

In [736]:
tree_envelope.head(5)

   co_id                                               geom
0    240  MULTIPOLYGON Z (((-5.25050 3.00000 3.69320, -5...
1    241  MULTIPOLYGON Z (((0.91650 -2.00000 2.46213, 0....
2    242  MULTIPOLYGON Z (((54.83300 -3.00000 2.46213, 5...
3    243  MULTIPOLYGON Z (((54.87475 -8.00000 2.46213, 5...
4    244  MULTIPOLYGON Z (((54.79125 -5.00000 3.28284, 5...

In [737]:
terrain_envelope.head(5)

,gmlid,id,geometry
0,ID_1989829a-9395-4709-ac9e-04dbb1830efa,672,"POLYGON Z ((0.00000 80.00000 0.00000, 0.00000 ..."
1,ID_c30a1ae5-19de-418e-ba38-aeba30dd9d3b,673,"POLYGON Z ((0.00000 80.00000 0.00000, 20.00000..."
2,ID_d962b2c5-d58b-4c9e-86fa-8dfc2a856dc3,677,"POLYGON Z ((60.00000 0.00000 0.00000, 60.00000..."
3,ID_bf3ba027-bb54-4790-9463-20cbe852f543,678,"POLYGON Z ((60.00000 0.00000 0.00000, 40.00000..."
4,ID_60d86271-61bd-4e40-85f2-daa889ec3efd,682,"POLYGON Z ((-40.00000 40.00000 0.00000, -40.00..."

## Download attributes data of buildings from the database

In [738]:
# Create a list containing buildings as index
building_list = geometry_envelope.drop_duplicates(subset = ["parent_gmlid"])[['building_id', 'parent_gmlid']].reset_index().drop(["index"], axis=1)

In [739]:
# Download attributes data of buildings from the database
num_residents_df = pd.read_sql_query("SELECT cityobject_id as building_id, CASE datatype WHEN 2 THEN intval END AS num_residents FROM citydb.cityobject_genericattrib WHERE attrname = 'num_residents'", db_engine)
lod2_volume_df = pd.read_sql_query("SELECT cityobject_id as building_id, CASE datatype WHEN 6 THEN realval END AS lod2_volume FROM citydb.cityobject_genericattrib WHERE attrname = 'lod2_volume'", db_engine)
building_type_df = pd.read_sql_query("SELECT cityobject_id as building_id, CASE datatype WHEN 1 THEN strval END AS building_type FROM citydb.cityobject_genericattrib WHERE attrname = 'building_type'", db_engine)
building_function_df = pd.read_sql_query("SELECT id AS building_id, function FROM citydb.building", db_engine)
building_year_of_construction_df = pd.read_sql_query("SELECT id AS building_id, EXTRACT(YEAR FROM year_of_construction) AS year_of_construction FROM citydb.building", db_engine)

In [740]:
# Merge the buildings list with attributes data
building_list = building_list.merge(num_residents_df, how='left').merge(lod2_volume_df, how='left').merge(building_function_df, how='left').merge(building_year_of_construction_df, how='left').merge(building_type_df, how='left')

In [741]:
# Remove buildings that are not residential buildings
building_list = building_list[building_list.function == "residential building"]

In [742]:
building_list

,building_id,parent_gmlid,num_residents,lod2_volume,function,year_of_construction,building_type
0,5,id_building_01,5.0,1250.0,residential building,1955.0,SFH
1,50,id_building_02,NaN,1250.0,residential building,1955.0,SFH
3,49,id_building_04,NaN,1250.0,residential building,1955.0,MFH
5,6,id_building_06,6.0,1250.0,residential building,1997.0,AB
6,21,id_building_07,110.0,1250.0,residential building,2005.0,AB
7,25,id_building_08,5.0,1250.0,residential building,1920.0,AB
8,4,id_building_11,12.0,1250.0,residential building,1920.0,MFH
9,77,id_building_12,34.0,1250.0,residential building,1964.0,MFH
10,82,id_buildingpart_09,20.0,1250.0,residential building,1965.0,AB
11,110,id_buildingpart_10,25.0,1250.0,residential building,1940.0,AB

In [743]:
# Define a function to calculate number of residents by volume and storey height 
def calculate_num_residents(lod2_volume,storeyHeightsAboveGround):
    floor_area = lod2_volume/storeyHeightsAboveGround
    density = 1/20 #1 person per 20 square meter
    num_residents = round(floor_area * density)
    return num_residents

In [744]:
# If the number of residents information doesn't exist, calculate it by function
building_list["num_residents"].fillna(calculate_num_residents(building_list["lod2_volume"], 3), inplace = True)

In [745]:
# Now we get a building list with complete attribute information
building_list

,building_id,parent_gmlid,num_residents,lod2_volume,function,year_of_construction,building_type
0,5,id_building_01,5.0,1250.0,residential building,1955.0,SFH
1,50,id_building_02,21.0,1250.0,residential building,1955.0,SFH
3,49,id_building_04,21.0,1250.0,residential building,1955.0,MFH
5,6,id_building_06,6.0,1250.0,residential building,1997.0,AB
6,21,id_building_07,110.0,1250.0,residential building,2005.0,AB
7,25,id_building_08,5.0,1250.0,residential building,1920.0,AB
8,4,id_building_11,12.0,1250.0,residential building,1920.0,MFH
9,77,id_building_12,34.0,1250.0,residential building,1964.0,MFH
10,82,id_buildingpart_09,20.0,1250.0,residential building,1965.0,AB
11,110,id_buildingpart_10,25.0,1250.0,residential building,1940.0,AB

## Download building, tree and terrain physics data from the database

In [746]:
Wall_type_constructionTypeId_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as outWalls_constructionTypeId FROM physics.building_type WHERE attribute = 'outWalls_constructionTypeId' and element is null", db_engine)
Wall_type_windowTypeId_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as outWalls_windowTypeId FROM physics.building_type WHERE attribute = 'outWalls_windowTypeId' and element is null", db_engine)
Wall_type_windowRatio_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as outWalls_windowRatio FROM physics.building_type WHERE attribute = 'outWalls_windowRatio' and element is null", db_engine)
Wall_type_uValue_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as outWalls_uValue FROM physics.building_type WHERE attribute = 'outWalls_uValue' and element is null", db_engine)
Wall_type_shortWaveReflectance_df = pd.read_sql_query("SELECT system, country, building_type, function, value as outWalls_shortWaveReflectance FROM physics.building_type WHERE attribute = 'outWalls_shortWaveReflectance' and element is null and year_initial is null and year_end is null", db_engine)
Wall_type_window_df = pd.read_sql_query("SELECT window_id AS outwalls_windowtypeid, u_value AS outwalls_GlazingUValue, g_value AS outwalls_GlazingGValue FROM physics.window", db_engine)
Wall_type_df = Wall_type_constructionTypeId_df.merge(Wall_type_windowTypeId_df, how='left').merge(Wall_type_windowRatio_df, how='left').merge(Wall_type_uValue_df, how='left').merge(Wall_type_shortWaveReflectance_df, how='left').merge(Wall_type_window_df, how='left')
Ground_type_constructionTypeId_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as groundShell_constructionTypeId FROM physics.building_type WHERE attribute = 'groundShell_constructionTypeId' and element is null", db_engine)
Ground_type_windowRatio_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as groundShell_windowRatio FROM physics.building_type WHERE attribute = 'groundShell_windowRatio' and element is null", db_engine)
Ground_type_uValue_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as groundShell_uValue FROM physics.building_type WHERE attribute = 'groundShell_uValue' and element is null", db_engine)
Ground_type_shortWaveReflectance_df = pd.read_sql_query("SELECT system, country, building_type, function, value as groundShell_shortWaveReflectance FROM physics.building_type WHERE attribute = 'groundShell_shortWaveReflectance' and element is null and year_initial is null and year_end is null", db_engine)
Ground_type_df = Ground_type_constructionTypeId_df.merge(Ground_type_windowRatio_df, how='left').merge(Ground_type_uValue_df, how='left').merge(Ground_type_shortWaveReflectance_df, how='left')
Roof_type_constructionTypeId_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as pitchedRoof_constructionTypeId FROM physics.building_type WHERE attribute = 'pitchedRoof_constructionTypeId' and element is null", db_engine)
Roof_type_windowTypeId_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as pitchedRoof_windowTypeId FROM physics.building_type WHERE attribute = 'pitchedRoof_windowTypeId' and element is null", db_engine)
Roof_type_windowRatio_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as pitchedRoof_windowRatio FROM physics.building_type WHERE attribute = 'pitchedRoof_windowRatio' and element is null", db_engine)
Roof_type_uValue_df = pd.read_sql_query("SELECT system, country, year_initial, year_end, building_type, function, value as pitchedRoof_uValue FROM physics.building_type WHERE attribute = 'pitchedRoof_uValue' and element is null", db_engine)
Roof_type_shortWaveReflectance_df = pd.read_sql_query("SELECT system, country, building_type, function, value as pitchedRoof_shortWaveReflectance FROM physics.building_type WHERE attribute = 'pitchedRoof_shortWaveReflectance' and element is null and year_initial is null and year_end is null", db_engine)
Roof_type_window_df = pd.read_sql_query("SELECT window_id AS pitchedRoof_windowtypeid, u_value AS pitchedRoof_GlazingUValue, g_value AS pitchedRoof_GlazingGValue FROM physics.window", db_engine)
Roof_type_df = Roof_type_constructionTypeId_df.merge(Roof_type_windowTypeId_df, how='left').merge(Roof_type_windowRatio_df, how='left').merge(Roof_type_uValue_df, how='left').merge(Roof_type_shortWaveReflectance_df, how='left').merge(Roof_type_window_df, how='left')
profile_df = pd.read_sql_query("SELECT * FROM physics.profile", db_engine)
occupancy_profile_df = pd.read_sql_query("SELECT DISTINCT profile_id AS occupancy_profile_id, system, country, function FROM physics.profile WHERE profile_type = 'occupancy'", db_engine)
composite_df = pd.read_sql_query("SELECT * FROM physics.composite", db_engine)
layer_df = pd.read_sql_query("SELECT system, country, material_id, density, heat_capacity, conductivity FROM physics.layer", db_engine)
tree_physics_df = pd.read_sql_query("SELECT * FROM physics.tree_physics", db_engine) 
terrain_physics_df = pd.read_sql_query("SELECT * FROM physics.terrain_physics", db_engine) 
heat_source_df = pd.read_sql_query("SELECT * FROM physics.heat_cool_source WHERE category = 'HeatSource'", db_engine)
cool_source_df = pd.read_sql_query("SELECT * FROM physics.heat_cool_source WHERE category = 'CoolSource'", db_engine)
heat_tank_df = pd.read_sql_query("SELECT * FROM physics.heat_cool_tank WHERE category = 'HeatTank'", db_engine)
cool_tank_df = pd.read_sql_query("SELECT * FROM physics.heat_cool_tank WHERE category = 'CoolTank'", db_engine)

In [747]:
# Merge the building physics tables to get a complete building physics table
building_type_df = Wall_type_df.merge(Ground_type_df, how='left').merge(Roof_type_df, how='left').merge(occupancy_profile_df, how='left')

In [749]:
building_type_df.head(5)

,system,country,year_initial,year_end,building_type,function,outwalls_constructiontypeid,outwalls_windowtypeid,outwalls_windowratio,outwalls_uvalue,outwalls_shortwavereflectance,outwalls_glazinguvalue,outwalls_glazinggvalue,groundshell_constructiontypeid,groundshell_windowratio,groundshell_uvalue,groundshell_shortwavereflectance,pitchedroof_constructiontypeid,pitchedroof_windowtypeid,pitchedroof_windowratio,pitchedroof_uvalue,pitchedroof_shortwavereflectance,pitchedroof_glazinguvalue,pitchedroof_glazinggvalue,occupancy_profile_id
0,TABULA,NL,0,1964,SFH,residential building,204.0,7.0,0.17,1.606,0.3,3.7,0.6,132.0,0.0,1.723,0.0,166.0,7.0,0.0,1.539,0.2,3.7,0.6,1
1,TABULA,NL,1965,1974,SFH,residential building,203.0,5.0,0.23,1.450,0.3,3.5,0.6,133.0,0.0,2.327,0.0,165.0,5.0,0.0,0.893,0.2,3.5,0.6,1
2,TABULA,NL,1975,1991,SFH,residential building,202.0,4.0,0.21,0.643,0.3,3.3,0.6,127.0,0.0,0.643,0.0,164.0,4.0,0.0,0.639,0.2,3.3,0.6,1
3,TABULA,NL,1992,2005,SFH,residential building,201.0,1.0,0.21,0.360,0.3,2.2,0.6,125.0,0.0,0.355,0.0,163.0,1.0,0.0,0.364,0.2,2.2,0.6,1
4,TABULA,NL,2006,2014,SFH,residential building,200.0,0.0,0.18,0.271,0.3,1.8,0.6,123.0,0.0,0.267,0.0,162.0,0.0,0.0,0.232,0.2,1.8,0.6,1

In [750]:
# Merge the building physics with building list
df = building_list.merge(building_type_df, on=['building_type','function'],how='left')
building_list = df[(df.year_of_construction >= df.year_initial) & (df.year_of_construction <= df.year_end)]
building_list = building_list.reset_index().drop(["index"], axis=1)

In [751]:
# Now we get a building list with complete attribute and physics information
building_list.head()

,building_id,parent_gmlid,num_residents,lod2_volume,function,year_of_construction,building_type,system,country,year_initial,year_end,outwalls_constructiontypeid,outwalls_windowtypeid,outwalls_windowratio,outwalls_uvalue,outwalls_shortwavereflectance,outwalls_glazinguvalue,outwalls_glazinggvalue,groundshell_constructiontypeid,groundshell_windowratio,groundshell_uvalue,groundshell_shortwavereflectance,pitchedroof_constructiontypeid,pitchedroof_windowtypeid,pitchedroof_windowratio,pitchedroof_uvalue,pitchedroof_shortwavereflectance,pitchedroof_glazinguvalue,pitchedroof_glazinggvalue,occupancy_profile_id
0,5,id_building_01,5.0,1250.0,residential building,1955.0,SFH,TABULA,NL,0,1964,204.0,7.0,0.17,1.606,0.3,3.7,0.6,132.0,0.0,1.723,0.0,166.0,7.0,0.0,1.539,0.2,3.7,0.6,1
1,50,id_building_02,21.0,1250.0,residential building,1955.0,SFH,TABULA,NL,0,1964,204.0,7.0,0.17,1.606,0.3,3.7,0.6,132.0,0.0,1.723,0.0,166.0,7.0,0.0,1.539,0.2,3.7,0.6,1
2,49,id_building_04,21.0,1250.0,residential building,1955.0,MFH,TABULA,NL,0,1964,204.0,4.0,0.26,1.606,0.3,3.3,0.6,132.0,0.0,1.723,0.0,166.0,4.0,0.0,1.539,0.2,3.3,0.6,1
3,6,id_building_06,6.0,1250.0,residential building,1997.0,AB,TABULA,NL,1992,2005,201.0,1.0,0.34,0.360,0.3,2.2,0.6,124.0,0.0,0.324,0.0,163.0,1.0,0.0,0.364,0.2,2.2,0.6,1
4,21,id_building_07,110.0,1250.0,residential building,2005.0,AB,TABULA,NL,1992,2005,201.0,1.0,0.34,0.360,0.3,2.2,0.6,124.0,0.0,0.324,0.0,163.0,1.0,0.0,0.364,0.2,2.2,0.6,1

## Shading surface

In [752]:
# Download a building list (include lod1 and lod2) from the database
shadingsurface_list = pd.read_sql_query("SELECT id AS cityobject_id, gmlid FROM citydb.cityobject WHERE objectclass_id = 26 or objectclass_id = 25", db_engine)
multipartbuilding_list = pd.read_sql_query("SELECT DISTINCT building_parent_id FROM citydb.building WHERE building_parent_id IS NOT NULL", db_engine)

In [753]:
# Remove multipart buildings from the building list (their single part buildings are already exist)
for i in multipartbuilding_list.index:
    for n in shadingsurface_list.index:
        if multipartbuilding_list["building_parent_id"].loc[i] == shadingsurface_list["cityobject_id"].loc[n]:
            shadingsurface_list = shadingsurface_list.drop(n)

In [754]:
# Remove lod2 buildings which will be simulated from the building list
for i in building_list.index:
    for n in shadingsurface_list.index:
        if building_list["parent_gmlid"].loc[i] == shadingsurface_list["gmlid"].loc[n]:
            shadingsurface_list = shadingsurface_list.drop(n)

In [755]:
# Download the building geometry (in lod1) from the database
surface_envelope_df = gpd.read_postgis("SELECT geometry, cityobject_id FROM citydb.surface_geometry WHERE geometry IS NOT NULL AND surface_geometry.geometry && st_makeenvelope(%s,%s,%s,%s,%s)"%(x_min_selection_buffer, y_min_selection_buffer, x_max_selection_buffer, y_max_selection_buffer, EPSG), db_engine, geom_col = "geometry")
shadingsurface_envelope = shadingsurface_list.merge(surface_envelope_df, how='left')

In [756]:
shadingsurface_envelope = shadingsurface_envelope[shadingsurface_envelope.geometry != None]

In [757]:
shadingsurface_envelope.head()

,cityobject_id,gmlid,geometry
0,3,id_box_building_27,"POLYGON Z ((-10.00000 20.00000 -5.00000, 10.00..."
1,3,id_box_building_27,"POLYGON Z ((-10.00000 20.00000 -5.00000, -10.0..."
2,3,id_box_building_27,"POLYGON Z ((-10.00000 20.00000 -5.00000, 10.00..."
3,3,id_box_building_27,"POLYGON Z ((10.00000 20.00000 -5.00000, 10.000..."
4,3,id_box_building_27,"POLYGON Z ((10.00000 30.00000 -5.00000, -10.00..."

In [758]:
shadingsurface_list = shadingsurface_envelope.drop_duplicates(subset=['gmlid'])

# Cut holes and Retriangulate the terrain TIN under simulated buildings

In [759]:
def convert_3D_2D(geometry):
    '''
    Takes a GeoSeries of 3D Multi/Polygons (has_z) and returns a list of 2D Multi/Polygons
    '''
    new_geo = []
    for p in geometry:
        if p.has_z:
            if p.geom_type == 'Polygon':
                lines = [xy[:2] for xy in list(p.exterior.coords)]
                new_p = Polygon(lines)
                new_geo.append(new_p)
            elif p.geom_type == 'MultiPolygon':
                new_multi_p = []
                for ap in p:
                    lines = [xy[:2] for xy in list(ap.exterior.coords)]
                    new_p = Polygon(lines)
                    new_multi_p.append(new_p)
                new_geo.append(MultiPolygon(new_multi_p))
    return new_geo
# Get the coordinates list for calculation
def coord_lister(geom):
    coords = list(geom.exterior.coords)
    return (coords)
# Define function to calculate Z value from original terrain TINs planes
def equation_plane_getZ(x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4):    
    a1 = x2 - x1
    b1 = y2 - y1
    c1 = z2 - z1
    a2 = x3 - x1
    b2 = y3 - y1
    c2 = z3 - z1
    a = b1 * c2 - b2 * c1
    b = a2 * c1 - a1 * c2
    c = a1 * b2 - b1 * a2
    d = (- a * x1 - b * y1 - c * z1)
    if c == 0:
        print('Error: surface is perpendicular to X-Y plane')
    else:
        return (-d - a * x4 - b * y4)/c

In [760]:
# Get the building footprint as holes
building_footprint_df = building_list[['parent_gmlid']]
building_footprint_df['objectclass_id'] = 35
building_footprint_df = building_footprint_df.merge(geometry_envelope, how = "left")[['parent_gmlid','objectclass_id','geometry']]
# Project footprints to 2D
building_footprint_df['2D_geometry'] = convert_3D_2D(building_footprint_df['geometry'])

In [761]:
building_footprint_df

,parent_gmlid,objectclass_id,geometry,2D_geometry
0,id_building_01,35,"POLYGON Z ((0.00000 0.00000 0.00000, 0.00000 1...","POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))"
1,id_building_02,35,"POLYGON Z ((20.00000 0.00000 0.00000, 10.00000...","POLYGON ((20 0, 10 0, 10 10, 20 10, 20 0))"
2,id_building_04,35,"POLYGON Z ((40.00000 0.00000 0.00000, 30.00000...","POLYGON ((40 0, 30 0, 30 10, 40 10, 40 0))"
3,id_building_06,35,"POLYGON Z ((60.00000 5.00000 0.00000, 60.00000...","POLYGON ((60 5, 60 15, 70 15, 70 5, 60 5))"
4,id_building_07,35,"POLYGON Z ((0.00000 -30.00000 0.00000, 0.00000...","POLYGON ((0 -30, 0 -20, 10 -20, 10 -30, 0 -30))"
5,id_building_08,35,"POLYGON Z ((20.00000 -25.00000 0.00000, 10.000...","POLYGON ((20 -25, 10 -25, 10 -15, 20 -15, 20 -..."
6,id_building_11,35,"POLYGON Z ((70.00000 -30.00000 0.00000, 60.000...","POLYGON ((70 -30, 60 -30, 60 -20, 70 -20, 70 -..."
7,id_building_12,35,"POLYGON Z ((70.00000 -15.00000 0.00000, 60.000...","POLYGON ((70 -15, 60 -15, 60 -5, 70 -5, 70 -15))"
8,id_buildingpart_09,35,"POLYGON Z ((40.00000 -25.00000 0.00000, 30.000...","POLYGON ((40 -25, 30 -25, 30 -15, 40 -15, 40 -..."
9,id_buildingpart_10,35,"POLYGON Z ((50.00000 -30.00000 0.00000, 40.000...","POLYGON ((50 -30, 40 -30, 40 -20, 50 -20, 50 -..."

In [762]:
# Project terrain to 2D
retri_df = terrain_envelope[['geometry']]
retri_df['2D_geometry'] = convert_3D_2D(retri_df ['geometry'])
retri_df.drop(['geometry'], axis=1, inplace=True)
retri_df.rename(columns={'2D_geometry': 'geometry'}, inplace=True)
retri_df = retri_df.head(len(retri_df))

In [763]:
retri_df.head(5)

                                            geometry
0  POLYGON ((0.00000 80.00000, 0.00000 60.00000, ...
1  POLYGON ((0.00000 80.00000, 20.00000 60.00000,...
2  POLYGON ((60.00000 0.00000, 60.00000 20.00000,...
3  POLYGON ((60.00000 0.00000, 40.00000 20.00000,...
4  POLYGON ((-40.00000 40.00000, -40.00000 20.000...

In [764]:
# Convert DataFrame to GeoDataaFrame
bf_inter_df = building_footprint_df[['2D_geometry']]
bf_inter_df.rename(columns = {'2D_geometry':'geometry'}, inplace = True)
bf_inter_df = GeoDataFrame(bf_inter_df, geometry='geometry')
# Find the intersect building foot print and dissolve them into one polygon to form a new foot print dataframe 
bf_inter_df_tem = bf_inter_df
bf_df = pd.DataFrame(columns=['geometry'])
while bf_inter_df_tem.empty is False:
    parent = bf_inter_df_tem['geometry'].loc[0]
    intersects_df = pd.DataFrame(bf_inter_df.intersects(parent))
    result = pd.concat([bf_inter_df, intersects_df], axis=1).reindex(bf_inter_df.index)
    result = result.loc[result[0] == True]
    footprint = result.dissolve()['geometry'].loc[0]
    polygons = pd.DataFrame([footprint])
    polygons = polygons.rename(columns = {0:'geometry'})
    bf_inter_df_tem = bf_inter_df_tem[~bf_inter_df_tem.geometry.isin(result.geometry)]
    bf_inter_df_tem = bf_inter_df_tem.reset_index().drop(["index"], axis=1)
    bf_df = pd.concat([bf_df, polygons])
bf_df = bf_df.reset_index().drop(["index"], axis=1)

In [765]:
# Cut holes, and retriangulate TINS below building foot print,
for i in bf_df.index:
    ring = bf_df['geometry'].loc[i]
    intersects_df = pd.DataFrame(retri_df.overlaps(ring))
    result = pd.concat([retri_df, intersects_df], axis=1).reindex(retri_df.index)
    result = result.loc[result[0] == True]
    for r in result.index:
        outter_polygon = result['geometry'].loc[r]
        ext_polygon = outter_polygon # exterior polygon
        int_polygon = ring # interior polygon
        multi_poly = ext_polygon.difference(int_polygon)
        if multi_poly.geom_type == 'MultiPolygon':
            for m in multi_poly:
                delauney = triangulate(m)
                polygons = pd.DataFrame(delauney)
                polygons = polygons.rename(columns = {0:'geometry'})
                retri_df = retri_df[~retri_df.geometry.isin(result.geometry)]
                retri_df = pd.concat([retri_df, polygons])
                retri_df = retri_df.reset_index().drop(["index"], axis=1)
        else:
            delauney = triangulate(multi_poly)
            polygons = pd.DataFrame(delauney)
            polygons = polygons.rename(columns = {0:'geometry'})
            retri_df = retri_df[~retri_df.geometry.isin(result.geometry)]
            retri_df = pd.concat([retri_df, polygons])
            retri_df = retri_df.reset_index().drop(["index"], axis=1)

# Remove holes from terrain
for i in bf_df.index:
    ring = bf_df['geometry'].loc[i]
    within_df = pd.DataFrame(retri_df.within(ring))
    result = pd.concat([retri_df, within_df], axis=1).reindex(retri_df.index)
    result = result.loc[result[0] == True]
    retri_df = retri_df[~retri_df.geometry.isin(result.geometry)]
retri_df = retri_df.reset_index().drop(["index"], axis=1)

In [766]:
retri_df['id'] = 0
for i in retri_df.index:
    geo_1 = retri_df['geometry'].loc[i]
    for r in terrain_envelope.index:
        geo_2 = terrain_envelope['geometry'].loc[r]
        if geo_1.difference(geo_2).is_empty:
            retri_df['id'].loc[i] = terrain_envelope['id'].loc[r]

In [767]:
# Final terrain TINs in 2D
retri_df.head()

                                            geometry   id
0  POLYGON ((0.00000 80.00000, 0.00000 60.00000, ...  672
1  POLYGON ((0.00000 80.00000, 20.00000 60.00000,...  673
2  POLYGON ((60.00000 0.00000, 60.00000 20.00000,...  677
3  POLYGON ((60.00000 0.00000, 40.00000 20.00000,...  678
4  POLYGON ((-40.00000 40.00000, -40.00000 20.000...  682

In [768]:
# Transform back to 3D terrain TINs
# Locate terrain TINs that needs to calculate Z value to be transformed to 3D
test_duplicate = pd.DataFrame(retri_df.id.duplicated())
for i in test_duplicate.index:
    if test_duplicate['id'].loc[i] == True:
        test_duplicate.at[i - 1,'id'] = True
# For terrain TINs without cutting holes, just replace the geometry with original 3D one
terrain_envelope.rename(columns = {'geometry':'geometry_3d'}, inplace = True)
retri_df = retri_df.merge(terrain_envelope,how='left')
# Locate terrain TINs that is single child to their parent TINs 
retri_df['geometry_2d'] = convert_3D_2D(retri_df['geometry_3d'])
for i in test_duplicate.index:
    if not retri_df['geometry_2d'].loc[i].difference(retri_df['geometry'].loc[i]).is_empty:
        test_duplicate.at[i,'id'] = True

In [769]:
# Calculate Z value and replace 2D terrain TINs with 3D terrain TINs
for i in retri_df.index:
    if test_duplicate['id'].loc[i] == True:
        POLY_2D = coord_lister(retri_df['geometry'].loc[i])
        POLY_3D = coord_lister(retri_df['geometry_3d'].loc[i])
        x1, y1, z1 = POLY_3D[0]
        x2, y2, z2 = POLY_3D[1]
        x3, y3, z3 = POLY_3D[2]
        Q = 0
        for r in POLY_2D:
            x4, y4 = r
            z4 = equation_plane_getZ(x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4)
            POLY_2D[Q] = POLY_2D[Q] + (z4,)
            Q = Q + 1
        POLY = Polygon(np.array(POLY_2D))
        retri_df.at[i, 'geometry_3d'] = POLY

In [770]:
retri_df = retri_df.drop('geometry', 1)
retri_df = retri_df.drop('geometry_2d', 1)
retri_df.rename(columns = {'geometry_3d':'geometry'}, inplace = True)

In [771]:
# Final terrain TINs in 3D
retri_df.head()

,id,gmlid,geometry
0,672,ID_1989829a-9395-4709-ac9e-04dbb1830efa,"POLYGON Z ((0.00000 80.00000 0.00000, 0.00000 ..."
1,673,ID_c30a1ae5-19de-418e-ba38-aeba30dd9d3b,"POLYGON Z ((0.00000 80.00000 0.00000, 20.00000..."
2,677,ID_d962b2c5-d58b-4c9e-86fa-8dfc2a856dc3,"POLYGON Z ((60.00000 0.00000 0.00000, 60.00000..."
3,678,ID_bf3ba027-bb54-4790-9463-20cbe852f543,"POLYGON Z ((60.00000 0.00000 0.00000, 40.00000..."
4,682,ID_60d86271-61bd-4e40-85f2-daa889ec3efd,"POLYGON Z ((-40.00000 40.00000 0.00000, -40.00..."

## Party walls processing

In [772]:
# Manage the one to one relationship (left building - left wall - right wall - right building)
generalization_df = pd.read_sql_query("SELECT * FROM citydb.generalization", db_engine)
df = pd.merge(generalization_df, geometry_envelope, on='cityobject_id', how="left")

In [773]:
# Check whether buildings are output residential buildings, and keep those   
df["exists_building_left"] = df["generalizes_to_id"].isin(building_list["building_id"])
df = df[df['exists_building_left'] == True]
df["exists_building_right"] = df["building_id"].isin(building_list["building_id"])
df = df[df['exists_building_right'] == True]

In [774]:
df.head()

,cityobject_id,generalizes_to_id,objectclass_id,building_id,lod2_multi_surface_id,gmlid,geometry,parent_gmlid,exists_building_left,exists_building_right
2,17,50,36,5,263,id_building_1_polygon_cs1,"POLYGON Z ((10.00000 10.00000 10.00000, 10.000...",id_building_01,True,True
6,115,82,36,110,649,id_building_9_polygon_cs1,"POLYGON Z ((40.00000 -20.00000 10.00000, 40.00...",id_buildingpart_10,True,True
7,34,25,36,21,264,id_building_7_polygon_cs1,"POLYGON Z ((10.00000 -20.00000 10.00000, 10.00...",id_building_07,True,True
8,37,21,36,25,266,id_building_7_polygon_cs1,"POLYGON Z ((10.00000 -20.00000 10.00000, 10.00...",id_building_08,True,True
9,96,110,36,82,580,id_building_9_polygon_cs1,"POLYGON Z ((40.00000 -20.00000 10.00000, 40.00...",id_buildingpart_09,True,True

In [775]:
# Remove those walls in geometry output list
Drop_ci = []
for i in df.index:
    Drop_ci.append(df['cityobject_id'].loc[i])
# Drop rows that contain any value in the list
geometry_envelope = geometry_envelope[geometry_envelope.cityobject_id.isin(Drop_ci) == False]

In [776]:
geometry_envelope.head()

,objectclass_id,building_id,lod2_multi_surface_id,gmlid,geometry,parent_gmlid,cityobject_id
0,34,5,286,id_building_1_polygon_5,"POLYGON Z ((0.00000 0.00000 0.00000, 10.00000 ...",id_building_01,51
1,33,5,99,id_building_1_polygon_2,"POLYGON Z ((5.00000 0.00000 15.00000, 10.00000...",id_building_01,12
2,34,5,274,id_building_1_polygon_4,"POLYGON Z ((0.00000 10.00000 0.00000, 0.00000 ...",id_building_01,44
4,35,5,135,id_building_1_polygon_3,"POLYGON Z ((0.00000 0.00000 0.00000, 0.00000 1...",id_building_01,15
5,33,5,86,id_building_1_polygon_1,"POLYGON Z ((0.00000 0.00000 10.00000, 5.00000 ...",id_building_01,7

## Check surfaces that will be simulated are convex or not. If not, retriangulate them.

In [777]:
# Function to check if the 3D polygon is convex ((input must be an array))
def is_convex(points):
        """
        Static method. Returns True if the polygon is convex regardless 
        of whether its vertices follow a clockwise or a 
        counter-clockwise order. This is a requirement for the rest of 
        the program.
        
        :param points: Points intented to form a polygon.
        :type points: ndarray with points xyz in rows
        :returns: Whether a polygon is convex or not.
        :rtype: bool
        
        .. note:: Despite the code works for ccw polygons, in order to 
            avoid possible bugs it is always recommended to use ccw 
            rather than cw.
            
        .. warning:: This method do not check the order of the points.
        """
        # Verification based on the cross product
        n_points = points.shape[0]
        i=-1
        u = points[i] - points[i-1]
        v = points[i+1] - points[i]
        last = np.sign(np.round(np.cross(u, v)))
        while i < n_points-1:
            u = points[i] - points[i-1]
            v = points[i+1] - points[i]
            s = np.sign(np.round(np.cross(u, v)))
            if abs((s - last).max()) > 1:
                return False
            last = s
            i += 2
        return True
# Function to check if the 3D plane is perpendicular to X-Y plane
def check_plane_perpendicular_to_XYplane(x1, y1, x2, y2,x3, y3):    
    a1 = x2 - x1
    b1 = y2 - y1
    a2 = x3 - x1
    b2 = y3 - y1
    c = a1 * b2 - b1 * a2
    if c == 0:
        return True
    else:
        return False
# Function to get the largest number out of three
def get_largest(a , b, c):
    if (a > b and a > c):
        return a
    elif (b > a and b > c):
        return b
    else:
        return c
# Function to get the smallest number out of three
def get_smallest(a , b, c):
    if (a < b and a < c):
        return a
    elif (b < a and b < c):
        return b
    else:
        return c
# Function to calculate 3D polygon area
# area of polygon poly (input must be a list or array)
def poly_area(poly):
    if len(poly) < 3: # not a plane - no area
        return 0
    total = [0, 0, 0]
    N = len(poly)
    for i in range(N):
        vi1 = poly[i]
        vi2 = poly[(i+1) % N]
        prod = np.cross(vi1, vi2)
        total[0] += prod[0]
        total[1] += prod[1]
        total[2] += prod[2]
    result = np.dot(total, unit_normal(poly[0], poly[1], poly[2]))
    return abs(result/2)
#unit normal vector of plane defined by points a, b, and c
def unit_normal(a, b, c):
    x = np.linalg.det([[1,a[1],a[2]],
             [1,b[1],b[2]],
             [1,c[1],c[2]]])
    y = np.linalg.det([[a[0],1,a[2]],
             [b[0],1,b[2]],
             [c[0],1,c[2]]])
    z = np.linalg.det([[a[0],a[1],1],
             [b[0],b[1],1],
             [c[0],c[1],1]])
    magnitude = (x**2 + y**2 + z**2)**.5
    return (x/magnitude, y/magnitude, z/magnitude)
# Define function to calculate X value from original terrain TINs planes
def equation_plane_getX(x1, y1, z1, x2, y2, z2, x3, y3, z3, y4, z4):    
    a1 = x2 - x1
    b1 = y2 - y1
    c1 = z2 - z1
    a2 = x3 - x1
    b2 = y3 - y1
    c2 = z3 - z1
    a = b1 * c2 - b2 * c1
    b = a2 * c1 - a1 * c2
    c = a1 * b2 - b1 * a2
    d = (- a * x1 - b * y1 - c * z1)
    if a == 0:
        print('Error: surface is perpendicular to X-Z plane')
    else:
        return (-d - c * z4 - b * y4)/a
# Define function to calculate Y value from original terrain TINs planes
def equation_plane_getY(x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, z4):    
    a1 = x2 - x1
    b1 = y2 - y1
    c1 = z2 - z1
    a2 = x3 - x1
    b2 = y3 - y1
    c2 = z3 - z1
    a = b1 * c2 - b2 * c1
    b = a2 * c1 - a1 * c2
    c = a1 * b2 - b1 * a2
    d = (- a * x1 - b * y1 - c * z1)
    if b == 0:
        print('Error: surface is perpendicular to Y-Z plane')
    else:
        return (-d - c * z4 - a * x4)/b
# Define function to flip a 2D polygon
def reverse_geom(geom):
    def _reverse(x, y, z=None):
        if z:
            return x[::-1], y[::-1], z[::-1]
        return x[::-1], y[::-1]

    return shapely.ops.transform(_reverse, geom)

In [778]:
new_data = pd.DataFrame()
for r in geometry_envelope.index:
    gem_list = coord_lister(geometry_envelope['geometry'].loc[r])
    gem_array = np.array(gem_list)
    # check if the surface is convex
    if is_convex(gem_array) is False:
        df = geometry_envelope.loc[[r]]
        n = 2
        # select three points from the surface that are not collinear
        polygon_check = np.vstack((gem_array[0], gem_array[1], gem_array[n]))
        while poly_area(polygon_check) == 0:
            n = n + 1
            polygon_check = np.vstack((gem_array[0], gem_array[1], gem_array[n]))
            if n > len(gem_array) - 1:
                print('Error: surface is not valid')
        x1,y1,z1 = gem_array[0]
        x2,y2,z2 = gem_array[1]
        x3,y3,z3 = gem_array[n]
        # check if the 3D plane formed by three points is perpendicular to X-Y plane
        if check_plane_perpendicular_to_XYplane(x1, y1, x2, y2,x3, y3) is True:
            # decide to project to XZ plane or YZ plane
            x_max = get_largest(x1 , x2, x3)
            x_min = get_smallest(x1 , x2, x3)
            y_max = get_largest(y1 , y2, y3)
            y_min = get_smallest(y1 , y2, y3)
            if x_max - x_min > y_max - y_min:
                # project to XZ plane
                pj_gem_list = []
                for i in gem_array:
                    i = np.delete(i, 1)
                    pj_gem_list.append(i)
                pj_gem_array = np.array(pj_gem_list)
                poly_pj = Polygon(pj_gem_array)
                delauney = triangulate(poly_pj)
                delauney = pd.DataFrame(delauney)
                # check the polygon orientation
                for m in delauney.index: 
                    if poly_pj.exterior.is_ccw != delauney[0].loc[m].exterior.is_ccw:
                        POLY_filp = reverse_geom(delauney[0].loc[m])
                        delauney.at[m, 0] = POLY_filp 
                for i in delauney.index:
                    if not delauney[0].loc[i].difference(poly_pj).is_empty:
                        delauney = delauney.drop(i)
                # Calculate Y value and project surface back to 3D
                for i in delauney.index:
                    POLY_2D = coord_lister(delauney[0].loc[i])
                    Q = 0
                    for r in POLY_2D:
                        x4, z4 = r
                        y4 = equation_plane_getY(x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, z4)
                        POLY_2D[Q] = POLY_2D[Q][:1] + (y4,) + POLY_2D[Q][1:]
                        Q = Q + 1
                    POLY = Polygon(np.array(POLY_2D))
                    delauney.at[i, 0] = POLY
            else:
                # project to YZ plane
                pj_gem_list = []
                for i in gem_array:
                    i = np.delete(i, 0)
                    pj_gem_list.append(i)
                pj_gem_array = np.array(pj_gem_list)
                poly_pj = Polygon(pj_gem_array)
                delauney = triangulate(poly_pj)
                delauney = pd.DataFrame(delauney)
                # check the polygon orientation
                for m in delauney.index: 
                    if poly_pj.exterior.is_ccw != delauney[0].loc[m].exterior.is_ccw:
                        POLY_filp = reverse_geom(delauney[0].loc[m])
                        delauney.at[m, 0] = POLY_filp 
                for i in delauney.index:
                    if not delauney[0].loc[i].difference(poly_pj).is_empty:
                        delauney = delauney.drop(i)
                # Calculate X value and project surface back to 3D
                for i in delauney.index:
                    POLY_2D = coord_lister(delauney[0].loc[i])
                    Q = 0
                    for r in POLY_2D:
                        y4, z4 = r
                        x4 = equation_plane_getX(x1, y1, z1, x2, y2, z2, x3, y3, z3, y4, z4)
                        POLY_2D[Q] = POLY_2D[Q][:0] + (x4,) + POLY_2D[Q][0:]
                        Q = Q + 1
                    POLY = Polygon(np.array(POLY_2D))
                    delauney.at[i, 0] = POLY
        else:
            # project to XY plane
            pj_gem_list = []
            for i in gem_array:
                i = np.delete(i, 2)
                pj_gem_list.append(i)
            pj_gem_array = np.array(pj_gem_list)
            poly_pj = Polygon(pj_gem_array)
            delauney = triangulate(poly_pj)
            delauney = pd.DataFrame(delauney)
            # check the polygon orientation
            for m in delauney.index: 
                if poly_pj.exterior.is_ccw != delauney[0].loc[m].exterior.is_ccw:
                    POLY_filp = reverse_geom(delauney[0].loc[m])
                    delauney.at[m, 0] = POLY_filp 
            for i in delauney.index:
                if not delauney[0].loc[i].difference(poly_pj).is_empty:
                    delauney = delauney.drop(i)
            # Calculate Z value and project surface back to 3D
            for i in delauney.index:
                POLY_2D = coord_lister(delauney[0].loc[i])
                Q = 0
                for r in POLY_2D:
                    x4, y4 = r
                    z4 = equation_plane_getZ(x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4)
                    POLY_2D[Q] = POLY_2D[Q] + (z4,)
                    Q = Q + 1
                POLY = Polygon(np.array(POLY_2D))
                delauney.at[i, 0] = POLY
        data = pd.DataFrame()
        for q in delauney.index:
            df_tem = df
            df_tem['geometry'] = delauney[0].loc[q]
            frames = [data, df_tem]
            data = pd.concat(frames)
        new_frames = [new_data, data]
        new_data = pd.concat(new_frames)
new_data = new_data.reset_index().drop(["index"], axis=1)

In [779]:
# Attaching gmlid to objects
m = 0
for i in new_data.index:
    new_data['gmlid'].loc[i] = "Polygon_new_" + str(m) + "_gmlid"
    m = m + 1

In [780]:
# Remove non_convex surfaces from geometry_envelope
for i in new_data.index:
    co_id = int(new_data['cityobject_id'].loc[i])
    geometry_envelope = geometry_envelope[geometry_envelope.cityobject_id != co_id]
# Add triangulated surfaces into geomery_envelope
frames = [geometry_envelope, new_data]
geometry_envelope = pd.concat(frames)
geometry_envelope = geometry_envelope.reset_index().drop(["index"], axis=1)

In [781]:
geometry_envelope.head()

,objectclass_id,building_id,lod2_multi_surface_id,gmlid,geometry,parent_gmlid,cityobject_id
0,34,5,286,id_building_1_polygon_5,"POLYGON Z ((0.00000 0.00000 0.00000, 10.00000 ...",id_building_01,51
1,33,5,99,id_building_1_polygon_2,"POLYGON Z ((5.00000 0.00000 15.00000, 10.00000...",id_building_01,12
2,34,5,274,id_building_1_polygon_4,"POLYGON Z ((0.00000 10.00000 0.00000, 0.00000 ...",id_building_01,44
3,35,5,135,id_building_1_polygon_3,"POLYGON Z ((0.00000 0.00000 0.00000, 0.00000 1...",id_building_01,15
4,33,5,86,id_building_1_polygon_1,"POLYGON Z ((0.00000 0.00000 10.00000, 5.00000 ...",id_building_01,7

# Write the xml file

## - Write the starter part

In [782]:
text = ''
text = text + '<?xml version="1.0" encoding="ISO-8859-1"?>\n'
text = text + '<CitySim name="test">\n'
text = text + '<Simulation beginMonth="1" endMonth="12" beginDay="1" endDay="31"/>\n'
text = text + '<Climate location="' + str(cli_input) + '"/>\n'
text = text + '<District>\n'

## - Write the composite part

In [783]:
# Form the composite information
outwalls_constructiontypeid_df = building_list[['outwalls_constructiontypeid']]
outwalls_constructiontypeid_df.rename({'outwalls_constructiontypeid': 'construction_id'}, axis=1, inplace=True)
groundshell_constructiontypeid_df = building_list[['groundshell_constructiontypeid']]
groundshell_constructiontypeid_df.rename({'groundshell_constructiontypeid': 'construction_id'}, axis=1, inplace=True)
pitchedroof_constructiontypeid_df = building_list[['pitchedroof_constructiontypeid']]
pitchedroof_constructiontypeid_df.rename({'pitchedroof_constructiontypeid': 'construction_id'}, axis=1, inplace=True)
construction_id_df = pd.concat([outwalls_constructiontypeid_df, groundshell_constructiontypeid_df, pitchedroof_constructiontypeid_df])
construction_id_df = construction_id_df.merge(composite_df[['construction_id', 'construction_name', 'construction_category']], on='construction_id', how='left')
construction_id_df = construction_id_df.drop_duplicates(subset=['construction_id'])

In [784]:
# Get the composite index
construction_id_df.head()

    construction_id construction_name construction_category
0             204.0         Wall_1,61               outWall
9             201.0         Wall_0,36               outWall
24            203.0         Wall_1,45               outWall
30            132.0        Floor_1,72           groundShell
39            124.0        Floor_0,32           groundShell

In [785]:
# Merge the layer information with composites
composite_write_df = construction_id_df.merge(composite_df, how='left').merge(layer_df, how='left')
composite_write_df.head()

,construction_id,construction_name,construction_category,id,system,country,material_id,attribute,data_type,value,uom,description,density,heat_capacity,conductivity
0,204.0,"Wall_1,61",outWall,280,TABULA,NL,0,thickness,float,0.200,None,None,2000.0,840.0,0.960
1,204.0,"Wall_1,61",outWall,281,TABULA,NL,23,thickness,float,0.011,None,None,105.0,1800.0,0.045
2,204.0,"Wall_1,61",outWall,282,TABULA,NL,62,thickness,float,0.000,None,None,1329.0,1014.0,0.790
3,201.0,"Wall_0,36",outWall,271,TABULA,NL,0,thickness,float,0.200,None,None,2000.0,840.0,0.960
4,201.0,"Wall_0,36",outWall,272,TABULA,NL,23,thickness,float,0.108,None,None,105.0,1800.0,0.045

In [786]:
for r in construction_id_df.index:
    text = text + '<Composite id="' + str(construction_id_df["construction_id"].loc[r]) + '" name="' + str(construction_id_df["construction_name"].loc[r]) + '" category="' + str(construction_id_df["construction_category"].loc[r]) + '">\n'
    for r1 in composite_write_df.index:
        if composite_write_df["construction_id"].loc[r1] == construction_id_df["construction_id"].loc[r]:
            text = text + '<Layer Thickness="' + str(composite_write_df["value"].loc[r1]) + '" Conductivity="' + str(composite_write_df["conductivity"].loc[r1]) + '" Cp="' + str(composite_write_df["heat_capacity"].loc[r1]) + '" Density="' + str(composite_write_df["density"].loc[r1]) + '" NRE="0" GWP="0" UBP="0"/>\n'
    text = text + '</Composite>\n'
# write the terrain groundsurface composite
text = text + '<Composite id="' + str(terrain_physics_df["composite_id"].loc[0]) + '" name="' + str(terrain_physics_df["name"].loc[0]) + '" category="' + str(terrain_physics_df["category"].loc[0]) + '">\n'
text = text + '<Layer Thickness="' + str(terrain_physics_df["thickness"].loc[0]) + '" Conductivity="' + str(terrain_physics_df["conductivity"].loc[0]) + '" Cp="' + str(terrain_physics_df["cp"].loc[0]) + '" Density="' + str(terrain_physics_df["density"].loc[0]) + '" NRE="0" GWP="0" UBP="0"/>\n'
text = text + '</Composite>\n'

## - Write the profile part

In [787]:
profile_write_df = building_list[['occupancy_profile_id']]
profile_write_df = profile_write_df.drop_duplicates(subset=['occupancy_profile_id'])
profile_write_df.rename({'occupancy_profile_id': 'profile_id'}, axis=1, inplace=True)
profile_write_df = profile_write_df.merge(profile_df, how='left')
profile_write_df = profile_write_df.sort_values('profile_id')

In [788]:
profile_write_df.head()

,profile_id,id,system,country,profile_type,element,function,data_type,length,value,description
0,1,0,TABULA,NL,occupancy,day,residential building,array,24,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 0.4, ...",occupancy day profile of residential buildings
1,1,1,TABULA,NL,occupancy,year,residential building,array,365,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",occupancy year profile of residential buildings

In [789]:
# define a function to write 24 values for day profile
def write_day(a):
    text = ''
    n = 1
    for i in a:
        text = text + 'p' + str(n) + '="' + str(i) + '" '
        n = n + 1
    return text
# define a function to write 365 values for year profile
def write_year(a):
    text = ''
    n = 1
    for i in a:
        text = text + 'd' + str(n) + '="' + str(i) + '" '
        n = n + 1
    return text

In [790]:
for r in profile_write_df.index:
    if profile_write_df["element"].loc[r] == 'day':
        text = text + '<OccupancyDayProfile id="' + str(profile_write_df["profile_id"].loc[r]) + '" name="' + str(profile_write_df["description"].loc[r]) + '" ' + str(write_day(profile_write_df["value"].loc[r])) + '/>\n'
    else:
        text = text + '<OccupancyYearProfile id="' + str(profile_write_df["profile_id"].loc[r]) + '" name="' + str(profile_write_df["description"].loc[r]) + '" ' + str(write_year(profile_write_df["value"].loc[r])) + '/>\n'

## - Write the geometry part

In [791]:
RN = int(input ("How many decimal places do you want to keep"))

How many decimal places do you want to keep 3

In [792]:
for r in building_list.index:
    text = text + '<Building id="' + str(building_list["building_id"].loc[r]) + '" key="' + str(building_list["parent_gmlid"].loc[r]) + '" Vi="' + str(building_list["lod2_volume"].loc[r]) + '" Ninf="0.1" BlindsLambda="0.2" BlindsIrradianceCutOff="100" Simulate="true">\n'
    text = text + '<HeatTank V="' + str(heat_tank_df["v"].loc[0]) + '" phi="' + str(heat_tank_df["phi"].loc[0]) + '" rho="' + str(heat_tank_df["rho"].loc[0]) + '" Cp="' + str(heat_tank_df["cp"].loc[0]) + '" Tmin="' + str(heat_tank_df["tmin"].loc[0]) + '" Tmax="' + str(heat_tank_df["tmax"].loc[0]) + '"/>\n'
    text = text + '<CoolTank V="' + str(cool_tank_df["v"].loc[0]) + '" phi="' + str(cool_tank_df["phi"].loc[0]) + '" rho="' + str(cool_tank_df["rho"].loc[0]) + '" Cp="' + str(cool_tank_df["cp"].loc[0]) + '" Tmin="' + str(cool_tank_df["tmin"].loc[0]) + '" Tmax="' + str(cool_tank_df["tmax"].loc[0]) + '"/>\n'
    text = text + '<HeatSource beginDay="' + str(heat_source_df["beginday"].loc[0]) + '" endDay="' + str(heat_source_df["endday"].loc[0]) + '">\n'
    text = text + '<Boiler name = "' + str(heat_source_df["name"].loc[0]) + '" Pmax="' + str(heat_source_df["pmax"].loc[0]) + '" eta_th="' + str(heat_source_df["eta_th"].loc[0]) + '"/>\n'
    text = text + '</HeatSource>\n'
    text = text + '<CoolSource beginDay="' + str(cool_source_df["beginday"].loc[0]) + '" endDay="' + str(cool_source_df["endday"].loc[0]) + '">\n'
    text = text + '<HeatPump Pmax="' + str(cool_source_df["pmax"].loc[0]) + '" eta_tech="' + str(cool_source_df["eta_tech"].loc[0]) + '" Ttarget="' + str(cool_source_df["ttarget"].loc[0]) + '" Tsource="' + str(cool_source_df["tsource"].loc[0]) + '"/>\n'
    text = text + '</CoolSource>\n'
    text = text + '<Zone id="' + str(r) + '" volume="' + str((building_list["lod2_volume"].loc[r]) * 0.8) + '" psi="0" Tmin="20" Tmax="26" groundFloor="true" nightVentilationBegin="0" nightVentilationEnd="0">\n'
    text = text + '<Occupants n="' + str(building_list["num_residents"].loc[r]) + '" sensibleHeat="90" sensibleHeatRadiantFraction="0.6" latentHeat="0" type="' + str(building_list["occupancy_profile_id"].loc[r]) + '"/>\n'
    for r1 in geometry_envelope.index:
        if geometry_envelope["objectclass_id"].loc[r1] == 34 and geometry_envelope["parent_gmlid"].loc[r1] == building_list["parent_gmlid"].loc[r]:
            text = text + '<Wall id="' + str(r1) + '" key="' + str(geometry_envelope["gmlid"].loc[r1]) + '" type="' + str(building_list["outwalls_constructiontypeid"].loc[r]) + '" ShortWaveReflectance="' + str(building_list["outwalls_shortwavereflectance"].loc[r]) + '" GlazingRatio="' + str(building_list["outwalls_windowratio"].loc[r]) + '" GlazingGValue="' + str(building_list["outwalls_glazinggvalue"].loc[r]) + '" GlazingUValue="' + str(building_list["outwalls_glazinguvalue"].loc[r]) + '" OpenableRatio="0">\n'
            v = 0
            for n in range(len(geometry_envelope["geometry"].loc[r1].exterior.coords)-1):
                text = text + '<V' + str(v) +' x="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][0] - float(x_min_selection), RN)) + '" y="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][1] - float(y_min_selection), RN)) + '" z="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][2], RN)) + '"/>\n'
                v = v + 1
            text = text + '</Wall>\n'
        elif geometry_envelope["objectclass_id"].loc[r1] == 36 and geometry_envelope["parent_gmlid"].loc[r1] == building_list["parent_gmlid"].loc[r]:
            text = text + '<Wall id="' + str(r1) + '" key="' + str(geometry_envelope["gmlid"].loc[r1]) + '" type="' + str(building_list["outwalls_constructiontypeid"].loc[r]) + '" ShortWaveReflectance="' + str(building_list["outwalls_shortwavereflectance"].loc[r]) + '" GlazingRatio="' + str(building_list["outwalls_windowratio"].loc[r]) + '" GlazingGValue="' + str(building_list["outwalls_glazinggvalue"].loc[r]) + '" GlazingUValue="' + str(building_list["outwalls_glazinguvalue"].loc[r]) + '" OpenableRatio="0">\n'
            v = 0
            for n in range(len(geometry_envelope["geometry"].loc[r1].exterior.coords)-1):
                text = text + '<V' + str(v) +' x="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][0] - float(x_min_selection), RN)) + '" y="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][1] - float(y_min_selection), RN)) + '" z="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][2], RN)) + '"/>\n'
                v = v + 1
            text = text + '</Wall>\n'
        elif geometry_envelope["objectclass_id"].loc[r1] == 35 and geometry_envelope["parent_gmlid"].loc[r1] == building_list["parent_gmlid"].loc[r]:
            text = text + '<Floor id="' + str(r1) + '" key="' + str(geometry_envelope["gmlid"].loc[r1]) + '" type="' + str(building_list["groundshell_constructiontypeid"].loc[r]) + '" ShortWaveReflectance="' + str(building_list["groundshell_shortwavereflectance"].loc[r]) + '" GlazingRatio="' + str(building_list["groundshell_windowratio"].loc[r]) + '" GlazingGValue="0" GlazingUValue="0" OpenableRatio="0">\n'
            v = 0
            for n in range(len(geometry_envelope["geometry"].loc[r1].exterior.coords)-1):
                text = text + '<V' + str(v) +' x="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][0] - float(x_min_selection), RN)) + '" y="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][1] - float(y_min_selection), RN)) + '" z="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][2], RN)) + '"/>\n'
                v = v + 1
            text = text + "</Floor>\n"
        elif geometry_envelope["objectclass_id"].loc[r1] == 33 and geometry_envelope["parent_gmlid"].loc[r1] == building_list["parent_gmlid"].loc[r]:
            text = text + '<Roof id="' + str(r1) + '" key="' + str(geometry_envelope["gmlid"].loc[r1]) + '" type="' + str(building_list["pitchedroof_constructiontypeid"].loc[r]) + '" ShortWaveReflectance="' + str(building_list["pitchedroof_shortwavereflectance"].loc[r]) + '" GlazingRatio="' + str(building_list["pitchedroof_windowratio"].loc[r]) + '" GlazingGValue="' + str(building_list["pitchedroof_glazinggvalue"].loc[r]) + '" GlazingUValue="' + str(building_list["pitchedroof_glazinguvalue"].loc[r]) + '" OpenableRatio="0" kFactor="0">\n'
            v = 0
            for n in range(len(geometry_envelope["geometry"].loc[r1].exterior.coords)-1):
                text = text + '<V' + str(v) +' x="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][0] - float(x_min_selection), RN)) + '" y="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][1] - float(y_min_selection), RN)) + '" z="' + str(round(geometry_envelope["geometry"].loc[r1].exterior.coords[n][2], RN)) + '"/>\n'
                v = v + 1
            text = text + '</Roof>\n'
    text = text + '</Zone>\n'
    text = text + '</Building>\n'

## - Write the ShadingSurface part

In [793]:
text = text + '<ShadingSurface>\n'
for r in shadingsurface_list.index:
    for r1 in shadingsurface_envelope.index:
        if shadingsurface_envelope["gmlid"].loc[r1] == shadingsurface_list["gmlid"].loc[r]:
            text = text + '<Surface id="' + str(r) + '" ShortWaveReflectance="0.2">\n'
            v = 0
            for n in range(len(shadingsurface_envelope["geometry"].loc[r1].exterior.coords)-1):
                text = text + '<V' + str(v) +' x="' + str(round(shadingsurface_envelope["geometry"].loc[r1].exterior.coords[n][0] - float(x_min_selection), RN)) + '" y="' + str(round(shadingsurface_envelope["geometry"].loc[r1].exterior.coords[n][1] - float(y_min_selection), RN)) + '" z="' + str(round(shadingsurface_envelope["geometry"].loc[r1].exterior.coords[n][2], RN)) + '"/>\n'
                v = v + 1
            text = text + '</Surface>\n'
text = text + '</ShadingSurface>\n'

## - Write the Tree part

In [794]:
text = text + '<Trees>\n'
for r in tree_envelope.index:
    text = text + '<Tree id="' + str(tree_envelope["co_id"].loc[r]) + '" name="' + str(tree_physics_df["category"].loc[0]) + '" leafAreaIndex="' + str(tree_physics_df["leaf_area_index"].loc[0]) + '" leafWidth="' + str(tree_physics_df["leaf_width"].loc[0]) + '" leafDistance="' + str(tree_physics_df["leaf_distance"].loc[0]) + '" deciduous="false">\n'
    for i in range(len(tree_envelope["geom"].loc[r])):
        text = text + '<Leaf id="' + str(tree_envelope["co_id"].loc[r]) + '" ShortWaveReflectance="' + str(tree_physics_df["short_wave_reflectance"].loc[0]) + '" LongWaveEmissivity="' + str(tree_physics_df["long_wave_emissivity"].loc[0]) + '">\n'
        v = 0
        for n in range(len(tree_envelope["geom"].loc[r][i].exterior.coords)-1):
            text = text + '<V' + str(v) +' x="' + str(round(tree_envelope["geom"].loc[r][i].exterior.coords[n][0] - float(x_min_selection), RN)) + '" y="' + str(round(tree_envelope["geom"].loc[r][i].exterior.coords[n][1] - float(y_min_selection), RN)) + '" z="' + str(round(tree_envelope["geom"].loc[r][i].exterior.coords[n][2], RN)) + '"/>\n'
            v = v + 1
        text = text + '</Leaf>\n'
    text = text + '</Tree>\n'
text = text + '</Trees>\n'

## - Write the Terrain part

In [795]:
text = text + '<GroundSurface>\n'
for r in retri_df.index:
    text = text + '<Ground id="' + str(retri_df["id"].loc[r]) + '" key="' + str(retri_df["gmlid"].loc[r]) + '" ShortWaveReflectance="' + str(terrain_physics_df["short_wave_reflectance"].loc[0]) + '" type="' + str(terrain_physics_df["composite_id"].loc[0]) + '" kFactor="' + str(terrain_physics_df["k_factor"].loc[0]) + '" detailedSimulation="true">\n'
    v = 0
    for n in range(len(retri_df['geometry'].loc[r].exterior.coords)-1):
        text = text + '<V' + str(v) +' x="' + str(round(retri_df['geometry'].loc[r].exterior.coords[n][0] - float(x_min_selection), RN)) + '" y="' + str(round(retri_df['geometry'].loc[r].exterior.coords[n][1] - float(y_min_selection), RN)) + '" z="' + str(round(retri_df['geometry'].loc[r].exterior.coords[n][2], RN)) + '"/>\n'
        v = v + 1
    text = text + '</Ground>\n'
text = text + '</GroundSurface>\n'
text = text + '</District>\n'
text = text + '</CitySim>\n'

In [796]:
# # Write the original terrain
# text = text + '<GroundSurface>\n'
# for r in terrain_envelope.index:
#     text = text + '<Ground id="' + str(terrain_envelope["id"].loc[r]) + '" key="' + str(terrain_envelope["gmlid"].loc[r]) + '" ShortWaveReflectance="' + str(terrain_physics_df["short_wave_reflectance"].loc[0]) + '" type="' + str(terrain_physics_df["composite_id"].loc[0]) + '" kFactor="' + str(terrain_physics_df["k_factor"].loc[0]) + '" detailedSimulation="true">\n'
#     v = 0
#     for n in range(len(terrain_envelope['geometry'].loc[r].exterior.coords)-1):
#         text = text + '<V' + str(v) +' x="' + str(round(terrain_envelope['geometry'].loc[r].exterior.coords[n][0] - float(x_min_selection), RN)) + '" y="' + str(round(terrain_envelope['geometry'].loc[r].exterior.coords[n][1] - float(y_min_selection), RN)) + '" z="' + str(round(terrain_envelope['geometry'].loc[r].exterior.coords[n][2], RN)) + '"/>\n'
#         v = v + 1
#     text = text + '</Ground>\n'
# text = text + '</GroundSurface>\n'
# text = text + '</District>\n'
# text = text + '</CitySim>\n'

In [797]:
text = text + '</District>\n'
text = text + '</CitySim>\n'
xml_file = open('C:/Users/JINYUZHEN/Desktop/result/output.xml', "w")
xml_file.write(text)
xml_file.close()

# Call Citysim and run the simulation

In [294]:
# Call CitySim ############################################################
print("Waking up CitySim...\n")
citysim_input = input ("What is the file path of CitySim solver?\n\n") #'C:/Users/JINYUZHEN/Desktop/citysim/CitySim.exe'
xml_input = input ("What is the file path of CitySim XML input file?\n\n") #'C:/Users/JINYUZHEN/Desktop/result/output.xml'

try:
    p = subprocess.Popen([citysim_input, xml_input], stderr=subprocess.PIPE)
    print("The simulation has begun!\n")
    # Print what CitySim solver is showing
    for line in p.stderr: 
        print(line.decode()) 
        if line.decode() == 'Simulation ended.\r\n':
            print("Results are being written...")

except Exception:
    print("Couldn't wake up CitySim. Please, check if CitySim solver is in the script's directory")
    time.sleep(5)
    sys.exit()

Waking up CitySim...

What is the file path of CitySim solver?

 C:/Users/JINYUZHEN/Desktop/citysim/CitySim.exe
What is the file path of CitySim XML input file?

 C:/Users/JINYUZHEN/Desktop/result/output.xml

The simulation has begun!

XML description file: C:/Users/JINYUZHEN/Desktop/result/output.xml

Reading XML file...

climate file = C:/Users/JINYUZHEN/Desktop/study/GEO2020/Python/EPW_citysim.cli

readClimate: C:/Users/JINYUZHEN/Desktop/study/GEO2020/Python/EPW_citysim.cli

Climate file opening

G_Dh and G_Bn provided.

reading of the data

No .cli2 weather file.

No .cli3 weather file.

	(Latitude: 52.2731 N, Longitude: 6.8908 E, Altitude: 34.6 m, Meridian: 1 h)

sprng seed: 26041978

begin day: 1	end day: 365

Added day profile with name empty day profile

Added year profile with name empty year profile

Added day profile with name empty day profile

Added year profile with name empty year profile

Loading Far Field Obstruction profile: no profile given.

Loading composite(s):

Walltype 204, Uvalue = 1.61871

Walltype 201, Uvalue = 0.360577

Walltype 203, Uvalue = 1.46104

Walltype 132, Uvalue = 1.8684

Walltype 124, Uvalue = 0.328947

Walltype 128, Uvalue = 1.20419

Walltype 130, Uvalue = 1.46104

Walltype 166, Uvalue = 1.48174

Walltype 163, Uvalue = 0.360577

Walltype 165, Uvalue = 0.873636

Walltype 999, Uvalue = 0.0647459

11 loaded.

Day id= 1: 1.0 1.0 1.0 1.0 1.0 1.0 0.8 0.6 0.4 0.4 0.4 0.6 0.8 0.6 0.4 0.4 0.6 0.8 0.8 0.8 0.8 1.0 1.0 1.0

Added day profile with name occupancy day profile of residential buildings

Occupancy DAY profiles: 1 loaded.

Loading occupancy YEAR profiles

Year id= 1: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

Added year profile with name occupancy year profile of residential buildings

Occupancy YEAR profiles: 1 loaded.

Loading Domestic Hot Water (DHW) DAY profiles

DHW DAY profiles: 0 loaded.

Loading Domestic Hot Water (DHW) YEAR profiles

DHW YEAR profiles: 0 loaded.

Loading district energy center(s) :

There are no DistrictEnergyCenters.

Loading geometry of building(s).

Building: 11	with key: id_building_01

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Zone: 0	Walls: 3	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 5

Zone creator.

Wall #0 Glazing Ratio: 0.17	Area: 125

Wall #1 Glazing Ratio: 0.17	Area: 100

Wall #2 Glazing Ratio: 0.17	Area: 125

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 290.5	Total window surface (m^2): 59.5	Total roof surface (m^2): 141.421

Total window conductance (W/K): 220.15	Total roof conductance (W/K): 209.55

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 5	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.17	Area: 125

Wall #1 Glazing Ratio: 0.17	Area: 100

Wall #2 Glazing Ratio: 0.17	Area: 125

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 290.5	Total window surface (m^2): 59.5	Total roof surface (m^2): 141.421

Total window conductance (W/K): 220.15	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Building: 20	with key: id_building_02

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Warning: In Surface id=9 repeated vertex V4, removing it.

Zone: 0	Walls: 5	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 21

Zone creator.

Wall #0 Glazing Ratio: 0.17	Area: 100

Wall #1 Glazing Ratio: 0.17	Area: 25

Wall #2 Glazing Ratio: 0.17	Area: 25

Wall #3 Glazing Ratio: 0.17	Area: 100

Wall #4 Glazing Ratio: 0.17	Area: 100

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 290.5	Total window surface (m^2): 59.5	Total roof surface (m^2): 141.421

Total window conductance (W/K): 220.15	Total roof conductance (W/K): 209.55

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 21	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.17	Area: 100

Wall #1 Glazing Ratio: 0.17	Area: 25

Wall #2 Glazing Ratio: 0.17	Area: 25

Wall #3 Glazing Ratio: 0.17	Area: 100

Wall #4 Glazing Ratio: 0.17	Area: 100

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 290.5	Total window surface (m^2): 59.5	Total roof surface (m^2): 141.421

Total window conductance (W/K): 220.15	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Building: 7	with key: id_building_04

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Warning: In Surface id=28 repeated vertex V4, removing it.

Zone: 0	Walls: 5	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 21

Zone creator.

Wall #0 Glazing Ratio: 0.26	Area: 100

Wall #1 Glazing Ratio: 0.26	Area: 100

Wall #2 Glazing Ratio: 0.26	Area: 125

Wall #3 Glazing Ratio: 0.26	Area: 100

Wall #4 Glazing Ratio: 0.26	Area: 25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 333	Total window surface (m^2): 117	Total roof surface (m^2): 141.421

Total window conductance (W/K): 386.1	Total roof conductance (W/K): 209.55

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 21	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.26	Area: 100

Wall #1 Glazing Ratio: 0.26	Area: 100

Wall #2 Glazing Ratio: 0.26	Area: 125

Wall #3 Glazing Ratio: 0.26	Area: 100

Wall #4 Glazing Ratio: 0.26	Area: 25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 333	Total window surface (m^2): 117	Total roof surface (m^2): 141.421

Total window conductance (W/K): 386.1	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Building: 34	with key: id_building_06

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Warning: In Surface id=40 repeated vertex V1, removing it.

Zone: 0	Walls: 5	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 6

Zone creator.

Wall #0 Glazing Ratio: 0.34	Area: 125

Wall #1 Glazing Ratio: 0.34	Area: 50

Wall #2 Glazing Ratio: 0.34	Area: 50

Wall #3 Glazing Ratio: 0.34	Area: 100

Wall #4 Glazing Ratio: 0.34	Area: 125

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 297	Total window surface (m^2): 153	Total roof surface (m^2): 141.421

Total window conductance (W/K): 336.6	Total roof conductance (W/K): 50.9933

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 6	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.34	Area: 125

Wall #1 Glazing Ratio: 0.34	Area: 50

Wall #2 Glazing Ratio: 0.34	Area: 50

Wall #3 Glazing Ratio: 0.34	Area: 100

Wall #4 Glazing Ratio: 0.34	Area: 125

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 297	Total window surface (m^2): 153	Total roof surface (m^2): 141.421

Total window conductance (W/K): 336.6	Total roof conductance (W/K): 50.9933

Vi: 1000

Zones loaded: 1

Building: 6	with key: id_building_07

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Warning: In Surface id=46 repeated vertex V1, removing it.

Zone: 0	Walls: 4	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 110

Zone creator.

Wall #0 Glazing Ratio: 0.34	Area: 125

Wall #1 Glazing Ratio: 0.34	Area: 50

Wall #2 Glazing Ratio: 0.34	Area: 125

Wall #3 Glazing Ratio: 0.34	Area: 100

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 264	Total window surface (m^2): 136	Total roof surface (m^2): 141.421

Total window conductance (W/K): 299.2	Total roof conductance (W/K): 50.9933

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 110	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.34	Area: 125

Wall #1 Glazing Ratio: 0.34	Area: 50

Wall #2 Glazing Ratio: 0.34	Area: 125

Wall #3 Glazing Ratio: 0.34	Area: 100

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 264	Total window surface (m^2): 136	Total roof surface (m^2): 141.421

Total window conductance (W/K): 299.2	Total roof conductance (W/K): 50.9933

Vi: 1000

Zones loaded: 1

Building: 67	with key: id_building_08

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Zone: 0	Walls: 7	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 5

Zone creator.

Wall #0 Glazing Ratio: 0.3	Area: 125

Wall #1 Glazing Ratio: 0.3	Area: 100

Wall #2 Glazing Ratio: 0.3	Area: 100

Wall #3 Glazing Ratio: 0.3	Area: 12.5

Wall #4 Glazing Ratio: 0.3	Area: 12.5

Wall #5 Glazing Ratio: 0.3	Area: 25

Wall #6 Glazing Ratio: 0.3	Area: 25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 280	Total window surface (m^2): 120	Total roof surface (m^2): 141.421

Total window conductance (W/K): 396	Total roof conductance (W/K): 209.55

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 5	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.3	Area: 125

Wall #1 Glazing Ratio: 0.3	Area: 100

Wall #2 Glazing Ratio: 0.3	Area: 100

Wall #3 Glazing Ratio: 0.3	Area: 12.5

Wall #4 Glazing Ratio: 0.3	Area: 12.5

Wall #5 Glazing Ratio: 0.3	Area: 25

Wall #6 Glazing Ratio: 0.3	Area: 25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 280	Total window surface (m^2): 120	Total roof surface (m^2): 141.421

Total window conductance (W/K): 396	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Building: 3	with key: id_building_11

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Zone: 0	Walls: 4	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 12

Zone creator.

Wall #0 Glazing Ratio: 0.26	Area: 125

Wall #1 Glazing Ratio: 0.26	Area: 100

Wall #2 Glazing Ratio: 0.26	Area: 125

Wall #3 Glazing Ratio: 0.26	Area: 100

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 333	Total window surface (m^2): 117	Total roof surface (m^2): 141.421

Total window conductance (W/K): 386.1	Total roof conductance (W/K): 209.55

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 12	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.26	Area: 125

Wall #1 Glazing Ratio: 0.26	Area: 100

Wall #2 Glazing Ratio: 0.26	Area: 125

Wall #3 Glazing Ratio: 0.26	Area: 100

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 333	Total window surface (m^2): 117	Total roof surface (m^2): 141.421

Total window conductance (W/K): 386.1	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Building: 63	with key: id_building_12

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Zone: 0	Walls: 4	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 34

Zone creator.

Wall #0 Glazing Ratio: 0.26	Area: 100

Wall #1 Glazing Ratio: 0.26	Area: 125

Wall #2 Glazing Ratio: 0.26	Area: 100

Wall #3 Glazing Ratio: 0.26	Area: 125

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 333	Total window surface (m^2): 117	Total roof surface (m^2): 141.421

Total window conductance (W/K): 386.1	Total roof conductance (W/K): 209.55

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 34	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.26	Area: 100

Wall #1 Glazing Ratio: 0.26	Area: 125

Wall #2 Glazing Ratio: 0.26	Area: 100

Wall #3 Glazing Ratio: 0.26	Area: 125

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 333	Total window surface (m^2): 117	Total roof surface (m^2): 141.421

Total window conductance (W/K): 386.1	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Building: 94	with key: id_buildingpart_09

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Zone: 0	Walls: 7	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 20

Zone creator.

Wall #0 Glazing Ratio: 0.45	Area: 125

Wall #1 Glazing Ratio: 0.45	Area: 100

Wall #2 Glazing Ratio: 0.45	Area: 100

Wall #3 Glazing Ratio: 0.45	Area: 6.25

Wall #4 Glazing Ratio: 0.45	Area: 12.5

Wall #5 Glazing Ratio: 0.45	Area: 25

Wall #6 Glazing Ratio: 0.45	Area: 25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 216.562	Total window surface (m^2): 177.188	Total roof surface (m^2): 141.421

Total window conductance (W/K): 637.875	Total roof conductance (W/K): 123.551

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 20	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.45	Area: 125

Wall #1 Glazing Ratio: 0.45	Area: 100

Wall #2 Glazing Ratio: 0.45	Area: 100

Wall #3 Glazing Ratio: 0.45	Area: 6.25

Wall #4 Glazing Ratio: 0.45	Area: 12.5

Wall #5 Glazing Ratio: 0.45	Area: 25

Wall #6 Glazing Ratio: 0.45	Area: 25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 216.562	Total window surface (m^2): 177.188	Total roof surface (m^2): 141.421

Total window conductance (W/K): 637.875	Total roof conductance (W/K): 123.551

Vi: 1000

Zones loaded: 1

Building: 110	with key: id_buildingpart_10

Heat Pump, COP (2C/5C): 27.815, COP (35C/5C): 2.7815

Air source.

Zone: 0	Walls: 7	Roofs: 2	Surfaces: 0	Floors: 1

Occupants defined: 25

Zone creator.

Wall #0 Glazing Ratio: 0.3	Area: 100

Wall #1 Glazing Ratio: 0.3	Area: 125

Wall #2 Glazing Ratio: 0.3	Area: 100

Wall #3 Glazing Ratio: 0.3	Area: 25

Wall #4 Glazing Ratio: 0.3	Area: 25

Wall #5 Glazing Ratio: 0.3	Area: 12.5

Wall #6 Glazing Ratio: 0.3	Area: 6.25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 275.625	Total window surface (m^2): 118.125	Total roof surface (m^2): 141.421

Total window conductance (W/K): 389.812	Total roof conductance (W/K): 209.55

Vi: 1000

Zone4N with 4 thermal nodes.

Zone occupants

Occupants number: 25	sensible heat convective: 0 W /radiative: 0 W

	latent heat: 0 W

NRE: 0 MJ	GWP: 0 kgCO2	UBP: 0 pts

Wall #0 Glazing Ratio: 0.3	Area: 100

Wall #1 Glazing Ratio: 0.3	Area: 125

Wall #2 Glazing Ratio: 0.3	Area: 100

Wall #3 Glazing Ratio: 0.3	Area: 25

Wall #4 Glazing Ratio: 0.3	Area: 25

Wall #5 Glazing Ratio: 0.3	Area: 12.5

Wall #6 Glazing Ratio: 0.3	Area: 6.25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 275.625	Total window surface (m^2): 118.125	Total roof surface (m^2): 141.421

Total window conductance (W/K): 389.812	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

10 loaded.

Loading wind turbine(s): 0 loaded.

Loading shading surface(s): 91 loaded.

Loading tree(s): 33 loaded.

Loading ground surface(s): 230 loaded.

District created.

Building 0	Zone: 0	Wall 0

Building 0	Zone: 0	Wall 1

Building 0	Zone: 0	Wall 2

Building 0	Zone: 0	Roof 0

Building 0	Zone: 0	Roof 1

Building 1	Zone: 0	Wall 0

Building 1	Zone: 0	Wall 1

Building 1	Zone: 0	Wall 2

Building 1	Zone: 0	Wall 3

Building 1	Zone: 0	Wall 4

Building 1	Zone: 0	Roof 0

Building 1	Zone: 0	Roof 1

Building 2	Zone: 0	Wall 0

Building 2	Zone: 0	Wall 1

Building 2	Zone: 0	Wall 2

Building 2	Zone: 0	Wall 3

Building 2	Zone: 0	Wall 4

Building 2	Zone: 0	Roof 0

Building 2	Zone: 0	Roof 1

Building 3	Zone: 0	Wall 0

Building 3	Zone: 0	Wall 1

Building 3	Zone: 0	Wall 2

Building 3	Zone: 0	Wall 3

Building 3	Zone: 0	Wall 4

Building 3	Zone: 0	Roof 0

Building 3	Zone: 0	Roof 1

Building 4	Zone: 0	Wall 0

Building 4	Zone: 0	Wall 1

Building 4	Zone: 0	Wall 2

Building 4	Zone: 0	Wall 3

Building 4	Zone: 0	Roof 0

Building 4	Zone: 0	Roof 1

Building 5	Zone: 0	Wall 0

Building 5	Zone: 0	Wall 1

Building 5	Zone: 0	Wall 2

Building 5	Zone: 0	Wall 3

Building 5	Zone: 0	Wall 4

Building 5	Zone: 0	Wall 5

Building 5	Zone: 0	Wall 6

Building 5	Zone: 0	Roof 0

Building 5	Zone: 0	Roof 1

Building 6	Zone: 0	Wall 0

Building 6	Zone: 0	Wall 1

Building 6	Zone: 0	Wall 2

Building 6	Zone: 0	Wall 3

Building 6	Zone: 0	Roof 0

Building 6	Zone: 0	Roof 1

Building 7	Zone: 0	Wall 0

Building 7	Zone: 0	Wall 1

Building 7	Zone: 0	Wall 2

Building 7	Zone: 0	Wall 3

Building 7	Zone: 0	Roof 0

Building 7	Zone: 0	Roof 1

Building 8	Zone: 0	Wall 0

Building 8	Zone: 0	Wall 1

Building 8	Zone: 0	Wall 2

Building 8	Zone: 0	Wall 3

Building 8	Zone: 0	Wall 4

Building 8	Zone: 0	Wall 5

Building 8	Zone: 0	Wall 6

Building 8	Zone: 0	Roof 0

Building 8	Zone: 0	Roof 1

Building 9	Zone: 0	Wall 0

Building 9	Zone: 0	Wall 1

Building 9	Zone: 0	Wall 2

Building 9	Zone: 0	Wall 3

Building 9	Zone: 0	Wall 4

Building 9	Zone: 0	Wall 5

Building 9	Zone: 0	Wall 6

Building 9	Zone: 0	Roof 0

Building 9	Zone: 0	Roof 1

Buildings' surfaces added to the scene.

Obstructing surfaces added to the scene.

Trees surfaces added to the scene.

Ground surfaces added to the scene.

Scene bounding sphere centre: (40,30,0) radius: 141.421

Smallest surface radius: 0.824687

Pixels per metre: 14.551

Direct renderer window dimension: 4115

View factors calculated.

Building inter-reflection matrix.

Number of surfaces: 1184

Number of reflections: 2

Compressed Row Storage inter-reflections Sparse Matrix ready.

Surfaces: 1184	Non-zero elements: 18322	Average non-zero elements / surface: 15.4747

OpenMP max threads: 8

Wall #0 Glazing Ratio: 0.17	Area: 125

Wall #1 Glazing Ratio: 0.17	Area: 100

Wall #2 Glazing Ratio: 0.17	Area: 125

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 290.5	Total window surface (m^2): 59.5	Total roof surface (m^2): 141.421

Total window conductance (W/K): 220.15	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Wall #0 Glazing Ratio: 0.17	Area: 100

Wall #1 Glazing Ratio: 0.17	Area: 25

Wall #2 Glazing Ratio: 0.17	Area: 25

Wall #3 Glazing Ratio: 0.17	Area: 100

Wall #4 Glazing Ratio: 0.17	Area: 100

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 290.5	Total window surface (m^2): 59.5	Total roof surface (m^2): 141.421

Total window conductance (W/K): 220.15	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Wall #0 Glazing Ratio: 0.26	Area: 100

Wall #1 Glazing Ratio: 0.26	Area: 100

Wall #2 Glazing Ratio: 0.26	Area: 125

Wall #3 Glazing Ratio: 0.26	Area: 100

Wall #4 Glazing Ratio: 0.26	Area: 25

Roof #0 Glazing Ratio: 0	Area: 70.7107

Roof #1 Glazing Ratio: 0	Area: 70.7107

Total wall surface (m^2): 333	Total window surface (m^2): 117	Total roof surface (m^2): 141.421

Total window conductance (W/K): 386.1	Total roof conductance (W/K): 209.55

Vi: 1000

Zones loaded: 1

Wall #0 Glazing Ratio: 0.34	Area: 125

Wall #1 Glazing Ratio: 0.34	Area: 50

Wall #2 Glazing Ratio: 0.34	Area: 50


# Store the Qs simulation result to the database

In [713]:
# Read the results - Qs value from TH file
import re
out_df = pd.read_csv('C:/Users/JINYUZHEN/Desktop/result/output_TH.out',  sep='\t') # change file name
qs_cols = [col for col in out_df.columns if 'Qs' in col]
qs_df = pd.read_csv("C:/Users/JINYUZHEN/Desktop/result/output_TH.out",  sep='\t', usecols=qs_cols)
# Change column names
old_name = []
new_name = []
for column in qs_df:
    old_name.append(column)
for i in old_name:
    result = re.search('\((.*)\):', i)
    new_name.append(result.group(1))
qs_df.columns = new_name
qs_df.head()

,id_building_01,id_building_02,id_building_04,id_building_06,id_building_07,id_building_08,id_building_11,id_building_12,id_buildingpart_09,id_buildingpart_10
0,11716,10614,13724,7145,0,13691,14352,12932,14500,12147
1,11900,10819,13946,7189,0,13878,14567,13144,14627,12321
2,11966,10903,13979,7083,0,13879,14592,13167,14474,12311
3,11691,10631,13496,6622,0,13381,14110,12683,13642,11814
4,11780,10720,13622,6712,0,13507,14239,12809,13808,11936

In [714]:
data = []
for i in building_list.index:
    tem1 = [50006, building_list["parent_gmlid"].loc[i] + '_energydemand_01']
    tem2 = [50033, building_list["parent_gmlid"].loc[i] + '_energydemand_timeseries_01']
    tem3 = [50006, building_list["parent_gmlid"].loc[i] + '_energydemand_02']
    tem4 = [50033, building_list["parent_gmlid"].loc[i] + '_energydemand_timeseries_02']
    tem5 = [50006, building_list["parent_gmlid"].loc[i] + '_energydemand_03']
    tem6 = [50033, building_list["parent_gmlid"].loc[i] + '_energydemand_timeseries_03']
    data.append(tem1)
    data.append(tem2)
    data.append(tem3)
    data.append(tem4)
    data.append(tem5)
    data.append(tem6)
df_cityobject = pd.DataFrame(data, columns = ['objectclass_id', 'gmlid'])

In [715]:
df_cityobject.to_sql(name='cityobject', con = db_engine, if_exists='append', index=False)

In [716]:
df_ng_timeseries = pd.read_sql_query("SELECT cityobject.id, cityobject.objectclass_id FROM cityobject WHERE cityobject.objectclass_id = 50033", db_engine)
df_ng_timeseries["timevaluesprop_acquisitionme"] = 'simulation'
df_ng_timeseries["timevaluesprop_interpolation"] = 'constantInPrecedingInterval'

In [717]:
df_ng_timeseries.to_sql(name='ng_timeseries', con = db_engine, if_exists='append', index=False)

In [718]:
df_ng_regulartimeseries = pd.read_sql_query("SELECT cityobject.id, cityobject.gmlid FROM cityobject WHERE cityobject.objectclass_id = 50033", db_engine)
df_ng_regulartimeseries["timeinterval"] = 1
df_ng_regulartimeseries["timeinterval_unit"] = None
df_ng_regulartimeseries["values_"] = None
df_ng_regulartimeseries["values_uom"] = None
df_ng_regulartimeseries["timeperiodprop_beginposition"] = '2022-01-01 00:00:00'
df_ng_regulartimeseries["timeperiodproper_endposition"] = '2022-12-31 11:59:59'
for i in df_ng_regulartimeseries.index:
    if "timeseries_01" in df_ng_regulartimeseries['gmlid'].loc[i]:
        df_ng_regulartimeseries["timeinterval_unit"].loc[i] = 'hour'
        df_ng_regulartimeseries["values_uom"].loc[i] = 'Wh'
    if "timeseries_02" in df_ng_regulartimeseries['gmlid'].loc[i]:
        df_ng_regulartimeseries["timeinterval_unit"].loc[i] = 'month'
        df_ng_regulartimeseries["values_uom"].loc[i] = 'kWh'
    if "timeseries_03" in df_ng_regulartimeseries['gmlid'].loc[i]:
        df_ng_regulartimeseries["timeinterval_unit"].loc[i] = 'year'  
        df_ng_regulartimeseries["values_uom"].loc[i] = 'kWh'
df_ng_regulartimeseries = df_ng_regulartimeseries.drop(columns=['gmlid'])

In [719]:
# extract the simulation result value
m = 0
for i in building_list.index:
    for column in qs_df:
        if building_list['parent_gmlid'].loc[i] == column:
            hour_value = ''
            month_value = str(qs_df[column].values[0:744].sum() / 1000) + ' ' + str(qs_df[column].values[744:1416].sum() / 1000) + ' ' + str(qs_df[column].values[1416:2160].sum() / 1000) + ' ' + str(qs_df[column].values[2160:2880].sum() / 1000) + ' ' + str(qs_df[column].values[2880:3624].sum() / 1000) + ' ' + str(qs_df[column].values[3624:4344].sum() / 1000) + ' ' + str(qs_df[column].values[4344:5088].sum() / 1000) + ' ' + str(qs_df[column].values[5088:5832].sum() / 1000) + ' ' + str(qs_df[column].values[5832:6552].sum() / 1000) + ' ' + str(qs_df[column].values[6552:7296].sum() / 1000) + ' ' + str(qs_df[column].values[7296:8040].sum() / 1000) + ' ' + str(qs_df[column].values[8040:].sum() / 1000)
            year_value = str(np.sum(qs_df[column].values) / 1000)
            for q in qs_df[column].values:
                hour_value = hour_value + str(q) + ' '
            hour_value = hour_value[:-1]
            df_ng_regulartimeseries["values_"].loc[m] = hour_value
            m = m + 1
            df_ng_regulartimeseries["values_"].loc[m] = month_value
            m = m + 1
            df_ng_regulartimeseries["values_"].loc[m] = year_value
            m = m + 1

In [720]:
df_ng_regulartimeseries.to_sql(name='ng_regulartimeseries', con = db_engine, if_exists='append', index=False)

In [721]:
df_ng_cityobject = pd.DataFrame(building_list['building_id'])
df_ng_cityobject = df_ng_cityobject.rename(columns={'building_id': 'id'})

In [722]:
df_ng_cityobject.to_sql(name='ng_cityobject', con = db_engine, if_exists='append', index=False)

In [723]:
df_ng_energydemand = pd.read_sql_query("SELECT cityobject.id FROM cityobject WHERE cityobject.objectclass_id = 50006", db_engine)
df_ng_energydemand["cityobject_demands_id"] = None
df_ng_energydemand["enduse"] = 'spaceHeating'
df_ng_energydemand["energyamount_id"] = None
cityobject_demands_id = []
for i in building_list.index:
    cityobject_demands_id.append(building_list['building_id'].loc[i])
    cityobject_demands_id.append(building_list['building_id'].loc[i])
    cityobject_demands_id.append(building_list['building_id'].loc[i]) 
for i in df_ng_energydemand.index:
    df_ng_energydemand['energyamount_id'].loc[i] = df_ng_energydemand['id'].loc[i] + 1
    df_ng_energydemand['cityobject_demands_id'].loc[i] = cityobject_demands_id[i]

In [724]:
df_ng_energydemand.to_sql(name='ng_energydemand', con = db_engine, if_exists='append', index=False)

# Store the Irradiance simulation result to the database

In [803]:
# Read the results - Irradiance value from SW file
out_df = pd.read_csv('C:/Users/JINYUZHEN/Desktop/result/output_SW2.out',  sep='\t') # change file name
ir_cols = [col for col in out_df.columns if 'building' in col or 'Polygon' in col]
ir_df = pd.read_csv("C:/Users/JINYUZHEN/Desktop/result/output_SW2.out",  sep='\t', usecols=ir_cols)
# Change column names
old_name = []
new_name = []
for column in ir_df:
    old_name.append(column)
for i in old_name:
    result = re.search('\((.*)\):Irra', i)
    new_name.append(result.group(1))
ir_df.columns = new_name
# Change column names
old_name = []
new_name = []
for column in ir_df:
    old_name.append(column)
for i in old_name:
    result = re.search('\((.*)', i)
    new_name.append(result.group(1))
ir_df.columns = new_name
ir_df.head()

,id_building_1_polygon_4,id_building_1_polygon_7,id_building_1_polygon_5,id_building_1_polygon_1,id_building_1_polygon_2,id_building_2_polygon_7,Polygon_UUID_6b52b561-1122-4439-9121-cf191b5cf608,Polygon_UUID_a1c78b6b-ddc7-434a-9899-7638cbcb9f69,id_building_2_polygon_6,id_building_3_polygon_cs1,id_building_2_polygon_1,id_building_2_polygon_2,id_building_4_polygon_7,id_building_3_polygon_cs2,id_building_4_polygon_5,id_building_4_polygon_6,Polygon_UUID_2f5fa401-0cb3-49fd-9531-7ff5be802839,id_building_4_polygon_2,id_building_4_polygon_1,id_building_6_polygon_4,Polygon_UUID_122cde24-42cb-4e4b-9a2e-de9c99d92a03,id_building_5_polygon_cs1,id_building_6_polygon_6,id_building_6_polygon_5,id_building_6_polygon_1,id_building_6_polygon_2,id_building_7_polygon_4,Polygon_UUID_64b01d61-889b-4fbb-8d53-6ff5ee903b62,id_building_7_polygon_5,id_building_7_polygon_7,id_building_7_polygon_2,id_building_7_polygon_1,id_building_8_polygon_5,id_building_8_polygon_6,id_building_8_polygon_7,Polygon_new_0,Polygon_new_1,Polygon_new_2,Polygon_new_3,id_building_8_polygon_1,id_building_8_polygon_2,id_building_11_polygon_5,id_building_11_polygon_6,id_building_11_polygon_4,id_building_11_polygon_7,id_building_11_polygon_2,id_building_11_polygon_1,id_building_12_polygon_6,id_building_12_polygon_5,id_building_12_polygon_7,id_building_12_polygon_4,id_building_12_polygon_2,id_building_12_polygon_1,id_building_9_polygon_4,id_building_9_polygon_6,id_building_9_polygon_7,Polygon_new_4,Polygon_new_5,Polygon_new_6,Polygon_new_7,id_building_9_polygon_2,id_building_9_polygon_1,id_building_10_polygon_7,id_building_10_polygon_5,id_building_10_polygon_6,Polygon_new_8,Polygon_new_9,Polygon_new_10,Polygon_new_11,id_building_10_polygon_1,id_building_10_polygon_2
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [726]:
surface_gmlid = pd.read_sql_query("SELECT id AS cityobject_id, gmlid AS surface_gmlid FROM citydb.cityobject", db_engine)
geometry_envelope = geometry_envelope.merge(surface_gmlid, how='left')
geometry_envelope.head()

,objectclass_id,building_id,lod2_multi_surface_id,gmlid,geometry,parent_gmlid,cityobject_id,surface_gmlid
0,34,5,286,id_building_1_polygon_5,"POLYGON Z ((0.00000 0.00000 0.00000, 10.00000 ...",id_building_01,51,id_building_1_wallsurface_1
1,33,5,99,id_building_1_polygon_2,"POLYGON Z ((5.00000 0.00000 15.00000, 10.00000...",id_building_01,12,id_building_1_roofsurface_2
2,34,5,274,id_building_1_polygon_4,"POLYGON Z ((0.00000 10.00000 0.00000, 0.00000 ...",id_building_01,44,id_building_1_wallsurface_2
3,35,5,135,id_building_1_polygon_3,"POLYGON Z ((0.00000 0.00000 0.00000, 0.00000 1...",id_building_01,15,id_building_1_groundsurface_1
4,33,5,86,id_building_1_polygon_1,"POLYGON Z ((0.00000 0.00000 10.00000, 5.00000 ...",id_building_01,7,id_building_1_roofsurface_1

In [727]:
surface_df = geometry_envelope[['gmlid','geometry','surface_gmlid']]
index_to_keep = []
for i in surface_df.index:
    for column in ir_df:
        if surface_df['gmlid'].loc[i] in column:
            index_to_keep.append(i)
surface_df = surface_df.iloc[index_to_keep]
surface_df = surface_df.drop_duplicates(subset='gmlid', keep='first').reset_index().drop(["index"], axis=1)

In [576]:
surface_list = surface_df.surface_gmlid.unique()

In [577]:
data = []
for i in surface_list:
    tem1 = [50005, i + '_weatherdata_01']
    tem2 = [50033, i + '_weatherdata_timeseries_01']
    tem3 = [50005, i + '_weatherdata_02']
    tem4 = [50033, i + '_weatherdata_timeseries_02']
    tem5 = [50005, i + '_weatherdata_03']
    tem6 = [50033, i + '_weatherdata_timeseries_03']
    data.append(tem1)
    data.append(tem2)
    data.append(tem3)
    data.append(tem4)
    data.append(tem5)
    data.append(tem6)
df_cityobject = pd.DataFrame(data, columns = ['objectclass_id', 'gmlid'])

In [578]:
df_cityobject.to_sql(name='cityobject', con = db_engine, if_exists='append', index=False)

In [579]:
df_ng_timeseries = pd.read_sql_query("SELECT cityobject.id, cityobject.objectclass_id FROM cityobject WHERE cityobject.objectclass_id = 50033 and cityobject.gmlid LIKE '%%weatherdata%%'", db_engine)
df_ng_timeseries["timevaluesprop_acquisitionme"] = 'simulation'
df_ng_timeseries["timevaluesprop_interpolation"] = 'constantInPrecedingInterval'

In [580]:
df_ng_timeseries.to_sql(name='ng_timeseries', con = db_engine, if_exists='append', index=False)

In [581]:
df_ng_regulartimeseries = pd.read_sql_query("SELECT cityobject.id, cityobject.gmlid FROM cityobject WHERE cityobject.objectclass_id = 50033 and cityobject.gmlid LIKE '%%weatherdata%%'", db_engine)
df_ng_regulartimeseries["timeinterval"] = 1
df_ng_regulartimeseries["timeinterval_unit"] = None
df_ng_regulartimeseries["values_"] = None
df_ng_regulartimeseries["values_uom"] = None
df_ng_regulartimeseries["timeperiodprop_beginposition"] = '2022-01-01 00:00:00'
df_ng_regulartimeseries["timeperiodproper_endposition"] = '2022-12-31 11:59:59'
for i in df_ng_regulartimeseries.index:
    if "timeseries_01" in df_ng_regulartimeseries['gmlid'].loc[i]:
        df_ng_regulartimeseries["timeinterval_unit"].loc[i] = 'hour'
        df_ng_regulartimeseries["values_uom"].loc[i] = 'W/m2'
    if "timeseries_02" in df_ng_regulartimeseries['gmlid'].loc[i]:
        df_ng_regulartimeseries["timeinterval_unit"].loc[i] = 'month'
        df_ng_regulartimeseries["values_uom"].loc[i] = 'W/m2'
    if "timeseries_03" in df_ng_regulartimeseries['gmlid'].loc[i]:
        df_ng_regulartimeseries["timeinterval_unit"].loc[i] = 'year'  
        df_ng_regulartimeseries["values_uom"].loc[i] = 'W/m2'
df_ng_regulartimeseries = df_ng_regulartimeseries.drop(columns=['gmlid'])

In [583]:
def poly_area(poly):
    if len(poly) < 3: # not a plane - no area
        return 0
    total = [0, 0, 0]
    N = len(poly)
    for i in range(N):
        vi1 = poly[i]
        vi2 = poly[(i+1) % N]
        prod = np.cross(vi1, vi2)
        total[0] += prod[0]
        total[1] += prod[1]
        total[2] += prod[2]
    result = np.dot(total, unit_normal(poly[0], poly[1], poly[2]))
    return abs(result/2)

In [584]:
surface_list_df = pd.DataFrame(surface_list,columns=['surface_gmlid'])
surface_list_df["polygon"] = None
surface_list_df["polygon_area_weigh"] = None
for i in surface_list_df.index:
    polygon_list = []
    for n in surface_df.index:
        if surface_list_df['surface_gmlid'].loc[i] == surface_df['surface_gmlid'].loc[n]:
            polygon_list.append(surface_df['gmlid'].loc[n])
    surface_list_df["polygon"].loc[i] = polygon_list
for i in surface_list_df.index:
    if len(surface_list_df['polygon'].loc[i]) == 1:
        surface_list_df["polygon_area_weigh"].loc[i] = [1]
    else:
        area_sum = 0
        polygon_area_weigh = []
        for n in surface_list_df['polygon'].loc[i]:
            for r in surface_df.index:
                if surface_df['gmlid'].loc[r] == n:
                    gem_list = coord_lister(surface_df['geometry'].loc[r])
                    gem_array = np.array(gem_list)
                    area_sum = area_sum + poly_area(gem_array)
        for q in surface_list_df['polygon'].loc[i]:
            for s in surface_df.index:
                if surface_df['gmlid'].loc[s] == q:
                    gem_list = coord_lister(surface_df['geometry'].loc[s])
                    gem_array = np.array(gem_list)
                    area_poly = poly_area(gem_array)
                    polygon_area_weigh.append(round(area_poly/area_sum,2))
        surface_list_df["polygon_area_weigh"].loc[i] = polygon_area_weigh

In [585]:
for i in surface_list_df.index:
    if len(surface_list_df['polygon'].loc[i]) > 1:
        sum_column = ir_df[surface_list_df['polygon'].loc[i][0]]*surface_list_df['polygon_area_weigh'].loc[i][0]
        n = 1
        while n < len(surface_list_df['polygon'].loc[i]):
            sum_column = sum_column + ir_df[surface_list_df['polygon'].loc[i][n]]*surface_list_df['polygon_area_weigh'].loc[i][n]
            n = n + 1
        ir_df[surface_list_df['surface_gmlid'].loc[i]] = sum_column
ir_df.head()

,id_building_1_polygon_4,id_building_1_polygon_7,id_building_1_polygon_5,id_building_1_polygon_1,id_building_1_polygon_2,id_building_2_polygon_7,Polygon_UUID_6b52b561-1122-4439-9121-cf191b5cf608,Polygon_UUID_a1c78b6b-ddc7-434a-9899-7638cbcb9f69,id_building_2_polygon_6,id_building_3_polygon_cs1,id_building_2_polygon_1,id_building_2_polygon_2,id_building_4_polygon_7,id_building_3_polygon_cs2,id_building_4_polygon_5,id_building_4_polygon_6,Polygon_UUID_2f5fa401-0cb3-49fd-9531-7ff5be802839,id_building_4_polygon_2,id_building_4_polygon_1,id_building_6_polygon_4,Polygon_UUID_122cde24-42cb-4e4b-9a2e-de9c99d92a03,id_building_5_polygon_cs1,id_building_6_polygon_6,id_building_6_polygon_5,id_building_6_polygon_1,id_building_6_polygon_2,id_building_7_polygon_4,Polygon_UUID_64b01d61-889b-4fbb-8d53-6ff5ee903b62,id_building_7_polygon_5,id_building_7_polygon_7,id_building_7_polygon_2,id_building_7_polygon_1,id_building_8_polygon_5,id_building_8_polygon_6,id_building_8_polygon_7,Polygon_new_0,Polygon_new_1,Polygon_new_2,Polygon_new_3,id_building_8_polygon_1,id_building_8_polygon_2,id_building_11_polygon_5,id_building_11_polygon_6,id_building_11_polygon_4,id_building_11_polygon_7,id_building_11_polygon_2,id_building_11_polygon_1,id_building_12_polygon_6,id_building_12_polygon_5,id_building_12_polygon_7,id_building_12_polygon_4,id_building_12_polygon_2,id_building_12_polygon_1,id_building_9_polygon_4,id_building_9_polygon_6,id_building_9_polygon_7,Polygon_new_4,Polygon_new_5,Polygon_new_6,Polygon_new_7,id_building_9_polygon_2,id_building_9_polygon_1,id_building_10_polygon_7,id_building_10_polygon_5,id_building_10_polygon_6,Polygon_new_8,Polygon_new_9,Polygon_new_10,Polygon_new_11,id_building_10_polygon_1,id_building_10_polygon_2,id_building_8_wallsurface_2,id_building_9_wallsurface_1,id_building_10_wallsurface_2
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [586]:
# extract the simulation result value
m = 0
for i in surface_list_df.index:
    if len(surface_list_df['polygon'].loc[i]) == 1:
        for column in ir_df:
            if surface_list_df['polygon'].loc[i][0] == column:
                hour_value = ''
                month_value = str(round(ir_df[column].values[0:744].sum() / 744, 3)) + ' ' + str(round(ir_df[column].values[744:1416].sum() / 672,3)) + ' ' + str(round(ir_df[column].values[1416:2160].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[2160:2880].sum() / 720,3)) + ' ' + str(round(ir_df[column].values[2880:3624].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[3624:4344].sum() / 720,3)) + ' ' + str(round(ir_df[column].values[4344:5088].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[5088:5832].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[5832:6552].sum() / 720,3)) + ' ' + str(round(ir_df[column].values[6552:7296].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[7296:8040].sum() / 720,3)) + ' ' + str(round(ir_df[column].values[8040:].sum() / 744,3))
                year_value = str(round(np.sum(ir_df[column].values) / 8760,3))
                for q in ir_df[column].values:
                    hour_value = hour_value + str(q) + ' '
                hour_value = hour_value[:-1]
                df_ng_regulartimeseries["values_"].loc[m] = hour_value
                m = m + 1
                df_ng_regulartimeseries["values_"].loc[m] = month_value
                m = m + 1
                df_ng_regulartimeseries["values_"].loc[m] = year_value
                m = m + 1
    else:
        for column in ir_df:
            if surface_list_df['surface_gmlid'].loc[i] == column:
                hour_value = ''
                month_value = str(round(ir_df[column].values[0:744].sum() / 744, 3)) + ' ' + str(round(ir_df[column].values[744:1416].sum() / 672,3)) + ' ' + str(round(ir_df[column].values[1416:2160].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[2160:2880].sum() / 720,3)) + ' ' + str(round(ir_df[column].values[2880:3624].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[3624:4344].sum() / 720,3)) + ' ' + str(round(ir_df[column].values[4344:5088].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[5088:5832].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[5832:6552].sum() / 720,3)) + ' ' + str(round(ir_df[column].values[6552:7296].sum() / 744,3)) + ' ' + str(round(ir_df[column].values[7296:8040].sum() / 720,3)) + ' ' + str(round(ir_df[column].values[8040:].sum() / 744,3))
                year_value = str(round(np.sum(ir_df[column].values) / 8760,3))
                for q in ir_df[column].values:
                    hour_value = hour_value + str(q) + ' '
                hour_value = hour_value[:-1]
                df_ng_regulartimeseries["values_"].loc[m] = hour_value
                m = m + 1
                df_ng_regulartimeseries["values_"].loc[m] = month_value
                m = m + 1
                df_ng_regulartimeseries["values_"].loc[m] = year_value
                m = m + 1

In [587]:
df_ng_regulartimeseries.head()

,id,timeinterval,timeinterval_unit,values_,values_uom,timeperiodprop_beginposition,timeperiodproper_endposition
0,335,1,hour,0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 39.4188 68...,W/m2,2022-01-01 00:00:00,2022-12-31 11:59:59
1,337,1,month,17.855 37.613 58.99 110.414 139.363 134.286 14...,W/m2,2022-01-01 00:00:00,2022-12-31 11:59:59
2,339,1,year,76.737,W/m2,2022-01-01 00:00:00,2022-12-31 11:59:59
3,341,1,hour,0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 7.37095 18...,W/m2,2022-01-01 00:00:00,2022-12-31 11:59:59
4,343,1,month,5.933 11.472 17.916 30.374 39.062 42.947 41.81...,W/m2,2022-01-01 00:00:00,2022-12-31 11:59:59

In [588]:
df_ng_regulartimeseries.to_sql(name='ng_regulartimeseries', con = db_engine, if_exists='append', index=False)

In [589]:
surface_cityobject_id = pd.DataFrame(geometry_envelope,columns=['surface_gmlid','cityobject_id'])
surface_cityobject_id = surface_cityobject_id.drop_duplicates()
surface_list_df = surface_list_df.merge(surface_cityobject_id, how='left')

In [590]:
df_ng_cityobject = pd.DataFrame(surface_list_df['cityobject_id'])
df_ng_cityobject = df_ng_cityobject.rename(columns={'cityobject_id': 'id'})

In [591]:
df_ng_cityobject.to_sql(name='ng_cityobject', con = db_engine, if_exists='append', index=False)

In [592]:
df_ng_weatherdata = pd.read_sql_query("SELECT cityobject.id FROM cityobject WHERE cityobject.objectclass_id = 50005", db_engine)
df_ng_weatherdata["cityobject_weatherdata_id"] = None
df_ng_weatherdata["values_id"] = None
df_ng_weatherdata["weatherdatatype"] = 'globalSolarIrradiance'
cityobject_weatherdata_id = []
for i in surface_list_df.index:
    cityobject_weatherdata_id.append(surface_list_df['cityobject_id'].loc[i])
    cityobject_weatherdata_id.append(surface_list_df['cityobject_id'].loc[i])
    cityobject_weatherdata_id.append(surface_list_df['cityobject_id'].loc[i])
for i in df_ng_weatherdata.index:
    df_ng_weatherdata['values_id'].loc[i] = df_ng_weatherdata['id'].loc[i] + 1
    df_ng_weatherdata['cityobject_weatherdata_id'].loc[i] = cityobject_weatherdata_id[i]

In [593]:
df_ng_weatherdata.to_sql(name='ng_weatherdata', con = db_engine, if_exists='append', index=False)